### ISSUE TITLE
Dependency on alexa-skills-kit:alexa-skills-kit:1.1

### ISSUE THREAD

**Issue by philipmw** [amzn/alexa-skills-kit-java#1]
The Maven package `com.amazon.alexa:alexa-skills-kit:1.1` declares a dependency on `alexa-skills-kit:alexa-skills-kit:1.1`. This package is not available on Maven Central. The only way I've been able to compile software with the ASK is to have a local checkout of this repo's `repo` directory, then point my `pom.xml` to this local directory as a local repository.

My software still compiles when I remove the dependency on `alexa-skills-kit:alexa-skills-kit:1.1`, so is that dependency even valid? If it is, can you add it to Maven Central?

**Comment by barbeau** [comment]
+1 - seems like `alexa-skills-kit:alexa-skills-kit:1.1` is a bogus dependency?

**Comment by pvasudev-amzn** [comment]
Thanks. The dependency has existed on maven for a while, although it may not have been propagated through on maven when you first tried to access it.

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.amazon.alexa%22

**Comment by philipmw** [comment]
The link you gave does not address the problem. To recap, there's a bogus dependency on `alexa-skills-kit:alexa-skills-kit`. The problem still remains. Would you please reopen this issue?

**Comment by barbeau** [comment]
Agreed - if `alexa-skills-kit:alexa-skills-kit` existed, then this URL would return the artifact - instead, it returns no results:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22alexa-skills-kit%22

**Comment by hyandell** [comment]
Reopening.

**Comment by pvasudev-amzn** [comment]
The packages no longer depend on "alexa-skills-kit:alexa-skills-kit". Do you mind taking another look at the pom and point me to the dependency? Make sure you're looking at the latest version.

**Comment by philipmw** [comment]
On reviewing this, I see that two days after I opened this ticket (Dec 28th), the POM for `com.amazon.alexa:alexa-skills-kit:1.1` was updated. Now it doesn't declare any dependencies anymore, including the faulty dependency.

I updated my Alexa skill's dependency to version 1.1.2, and it builds without having to exclude `alexa-skills-kit:alexa-skills-kit` anymore.

Resolving.

**Comment by pvasudev-amzn** [comment]
Thanks Philip.
