### ISSUE TITLE
The SDK should use log4j 2.x

### ISSUE THREAD

**Issue by ansman** [amzn/alexa-skills-kit-java#129]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Seeing as the official [Amazon Lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html) recommends using log4j 2 I think the official SDK should do so too.

## Current Behavior
Currently slf4j is used which is backed by log4j 1

## Possible Solution
A migration to log4j shouldn't be too hard to implement.

## Context
Currently it's quite confusing that log4j 1 is pulled in to the classpath and it's easy to use the wrong one.

**Comment by breedloj** [comment]
I like this suggestion and am generally all in favor of using the latest versions of libraries but am concerned about the potential for breaking customer code since, as you mention, Slf4j & Log4j v1 are currently being surfaced on the classpath. Anyone using these transitive dependencies in their own Skill would be broken if we remove them. I'd be inclined to wait until the next major version bump to make this change.

**Comment by PyvesB** [comment]
Log4j v1 has reached end of life many years ago, and the last maintenance update is over 6 years old. The second generation fixes many issues and has significantly better performance, which is quite critical when is comes to Alexa skills developed using a JVM language. It's quite frustrating and confusing to have a modern SDK pull in such deprecated dependencies. I personally think this upgrade should be enacted as soon as possible. 😉

**Comment by ansman** [comment]
I agree with @PyvesB. What you could do is switch to log4j2 and keep log4j1 as a `runtime` dependency. That way you'd still be binary compatible but you'd remove log4j1 from the classpath.
Then for your next major release you can remove it altogether.

**Comment by breedloj** [comment]
PR #136 should address this without causing any breaking changes to folks.
