### ISSUE TITLE
Implementation specific dependencies should have the runtime scope

### ISSUE THREAD

**Issue by ansman** [amzn/alexa-skills-kit-java#130]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When using this library you should get transient dependencies as needed but not all of them needs to be added to the client's classpath.

## Current Behavior
Currently all (non test) dependencies are lacking a scope, which defaults to `compile`.

## Possible Solution
Go through the dependencies and add a `runtime` scope to the ones that shouldn't be public.
More info on scopes can be found here: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

## Context
When using this library you currently get a bunch of dependencies that shouldn't be externally visible such as slf4j, jackson, commons-io etc

**Comment by breedloj** [comment]
Thanks for the suggestion. Most of our dependencies are needed at compile time as they're referenced in code. But I have gone through and found a couple that were not; the biggest being the servlet-API dependency which can use the provided scope.

**Comment by ansman** [comment]
I see. Well, ideally `compile` would be used when compiling the `jar` for this SDK but the POM file that is published to the maven repository should use `runtime` since consumers of the SDK don't want them as a `compile` dependency but rather `runtime`. Does that make sense? Can it be done with maven?

It can be done when [using Gradle](https://docs.gradle.org/current/userguide/java_library_plugin.html) using the `api` and `implementation` dependencies. But perhaps this isn't possible using pure maven.

**Comment by breedloj** [comment]
Unfortunately Maven does not support anything like that. But I have merged in the aforementioned PR.

**Comment by ansman** [comment]
Too bad, besides having two separate POM files or switching to gradle there doesn't seem to be a solution to this. Thanks!
