### ISSUE TITLE
Builders should include mandatory parameters in their constructor

### ISSUE THREAD

**Issue by bgreen1005** [amzn/alexa-skills-kit-java#14]
The builders used in User, Session etc should be more verbose and include the mandatory parameters in the constructor.

For example, the `Session` cannot be built without the `sessionId` field being populated.
So, instead of a developer having to do: 

`Session.builder().withSessionId("session123").build()`;

why not have: 

`Session.builder("session123").build();`

or:

`Session.Builder.withSessionId("session123").build()`;

where `withSessionId` is the only public static method and returns a new `Builder`.

You could then rename the non-mandatory setters such as `withAttributes` to `andAttributes` to indicate which are mandatory and which are optional.

This would then look like:

`Session.Builder.withSessionId("session123").andAttributes(new HashMap<String, Object)());`

**Comment by jjaquinta** [comment]
Adding additional constructors would be fine. But replacing them wouldn't be backward compatible. 
What could be done (if it isn't already) is when .build() is called, that it validates that all the mandatory values are present, that all present values are in the correct format, or throw an IllegalArgumentException if not. That way it it is more likely to "fail quickly" if a programmer has a typo.

**Comment by sungolivia** [comment]
This is now supported in our current SDK with what @jjaquinta has mentioned.
