### ISSUE TITLE
Class com.amazon.ask.Skills not included in version. 2.5.5 jar

### ISSUE THREAD

**Issue by ToddMason** [amzn/alexa-skills-kit-java#144]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The jar ask-sdk-core-2.5.5.jar doesn't include the class com.amazon.ask.Skills 

The following is a snippet from my maven pom.xml

	**<dependency>
			<groupId>com.amazon.alexa</groupId>
			<artifactId>ask-sdk-lambda-support</artifactId>
			<version>2.5.5</version>
        </dependency>**

When I revert back to version 2.0.2 the jar file contains com.amazon.ask.Skills.

**Comment by Chris-Liao** [comment]
Hi, ask-sdk-core doesn't depend on Skills, https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk/src/com/amazon/ask/Skills.java, it's in ask-sdk module, you can add this dependency to your project, https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk/pom.xml. Thanks.

**Comment by ToddMason** [comment]
I see this in the Helloword example. 
<dependency>
      <groupId>com.amazon.alexa</groupId>
      <artifactId>ask-sdk-core</artifactId>
      <version>2.5.5</version>
    </dependency>

I have the same in my pom.xml. Shouldn't that do it?

**Comment by Chris-Liao** [comment]
@ToddMason are you referring to this [HellloWorld](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/samples/helloworld/pom.xml#L30-L36) sample? There is only one ask-sdk dependency.

**Comment by ToddMason** [comment]
Yes, sorry for some reason I had gotten confused and was using ask-sdk-core and not ask-sdk for my artifact id. I'm not having any issues now. Thanks, and again sorry for wasting your time.

**Comment by Chris-Liao** [comment]
@ToddMason no problem, closing this issue and feel free to open for any questions. Thanks.
