### ISSUE TITLE
Required slots functionnality

### ISSUE THREAD

**Issue by PyvesB** [amzn/alexa-skills-kit-java#145]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Context
I have marked one of my Skill's slots as required in the Alexa developer console, as per the [Alexa documentation](https://developer.amazon.com/fr/docs/custom-skills/define-the-dialog-to-collect-and-confirm-required-information.html#id-required-slots). I'm now looking into the implementation side of things. I didn't find anything pertaining to required slots in the samples and tutorials listed in the Readme of this repository, so I tried writing a simple handler function that builds a response by calling the `addElicitSlotDirective` method:
````
@Override
public Optional<Response> handle(HandlerInput input) {
  Intent intent = ((IntentRequest) input.getRequestEnvelope().getRequest()).getIntent();
  ResponseBuilder responseBuilder = input.getResponseBuilder();

  if (intent.getSlots().get("some_slot").getValue() == null) {
    return responseBuilder.addElicitSlotDirective("some_slot", intent).build();
  }
  return responseBuilder.withSpeech("The slot was found").withShouldEndSession(true).build();
}
````
I'm unsure as to what I have to pass in for the intent parameter of `addElicitSlotDirective`, the Javadocs are not helpful here. The code snippet above simply uses the input intent.

Unfortunately this is not working, Alexa simply indicates that there was an error with the Skill's response. The logs of my Lambda function, even set to trace, don't display any useful information.

## Your Environment

* ASK Java SDK version used: 2.5.5

## Java Info

* Java version used for development: 8

**Comment by Chris-Liao** [comment]
Hi @PyvesB, here is more about [Dialog model](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html) interface, you can find information about Dialog model structure and interaction examples. 

There are 4 directives you can use in Dialog, DelegateDirective, ElicitSlotDirective, ConfirmSlotDirective, ConfirmIntentDirective. When you mark a slot as required, you can either return DelegateDirective, which uses prompts you define in interaction model, or ElicitSlotDirective, which you can provide prompt in code. When you make a slot or intent require confirmation, then you need ConfirmSlotDirective, ConfirmIntentDirective.

When you're handling request, if the user has provided a response, then `slot.getValue() != null`,  you may need to verify confirmationStatus or resolutions ([JSON reference)](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#intentrequest) instead. 

I hope the below code snippet can help you:

```
        Map<String, Slot> slots = intent.getSlots();       
        Set<Slot> unconfirmedSlots = slots.values().stream()
            .filter(slot ->
                slot.getConfirmationStatus() != SlotConfirmationStatus.CONFIRMED)
            .collect(Collectors.toSet());

        for(Slot slot : unconfirmedSlots) {
            return handlerInput.getResponseBuilder()
                    .addElicitSlotDirective("some_slot", intent)
                    .withSpeech("you prompt here.")
                    .build();
        }

        //return prompts defined in interaction model
        return handlerInput.getResponseBuilder()
                .addDelegateDirective(intent)                 
                .build();
```

We also have a [Decision Tree sample skill ](https://github.com/alexa-labs/ask-sdk-frameworks-java/blob/master/samples/decisiontree/src/main/java/com/amazon/ask/decisiontree/controllers/DecisionTreeController.java#L95-L123)using MVC framework, which uses DelegateDirective and ElicitSlotDirective. I hope this can help you better understand.

**Comment by PyvesB** [comment]
I got confused about the difference between `ElicitSlotDirective` and `DelegateDirective`. Thank you for the detailed help and clarification @Chris-Liao! 👍
