### ISSUE TITLE
Provide overloaded withStandardCard(StandardCard card) method for ResponseBuilder

### ISSUE THREAD

**Issue by paulschuetz** [amzn/alexa-skills-kit-java#148]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

ResponseBuilder should provide an overloading of the withStandardCard(String title, String text, Image image) method, where I can just pass in a preconstructed StandardCard.
## Current Behavior

I have a class with preconstructured Card's and I can not just pass them into the withStandardCard method, so I have to manually set heading, text and image every time.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
Just construct a Response using the handlerInput's RequestBuilder
## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
Provide an overloading for the builder method

## Your Environment

* ASK Java SDK version used: 2.7.1
* Operating System and version:
Windows 10
## Java Info

* Java version used for development: Java 8

**Comment by nikhilym** [comment]
Hey @paulschuetz , thanks for the feature request. We will look into adding this function in the Response Builder

**Comment by Chris-Liao** [comment]
Hey @paulschuetz, we've added a withCard method in ResponseBuilder so that you can pass pre-constructed Card object or its subclass like SimpleCard and StandardCard into response. 
This pull request https://github.com/alexa/alexa-skills-kit-sdk-for-java/pull/155 has been merged, we will include it in next release. Please stay tuned.

**Comment by paulschuetz** [comment]
Great! Thanks for implementing my desired functionality 👍
