### ISSUE TITLE
Provide an Optional<String>getSlot(String slotName) method

### ISSUE THREAD

**Issue by paulschuetz** [amzn/alexa-skills-kit-java#149]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

IntentRequest exposes a Optional<String>getSlot(String slotName) method to easily access the slot values and react on their absence.
## Current Behavior

Right now you have to write 4 lines of code in order to retrieve a slot value.

## Steps to Reproduce (for bugs)
```
        IntentRequest intent = (IntentRequest) handlerInput.getRequestEnvelope().getRequest();
        Slot nameSlot = intent.getIntent().getSlots().get(Slots.NAME);
        if (nameSlot == null || nameSlot.getValue()==null) return getNoNameSpecifiedResponse(handlerInput);
        String name = nameSlot.getValue();
```
## Possible Solution
Provide a Optional<String> getSlot(String slotname) method
## Your Environment

* ASK Java SDK version used: 2.7.1
* Operating System and version: Windows 10

## Java Info

* Java version used for development: Java 8

**Comment by breedloj** [comment]
Thanks for the feature request Paul. Making it easier to pull out request attributes scoped to particular request types is something I am interested in. At the same time I want to avoid making one-off utility methods to handle every case. Let me give this some thought and see if I can come up with something more generic that can help out across the board.

**Comment by breedloj** [comment]
Release 2.9.1 makes typed request handler interfaces available to give skill developers a type safe way to write handlers for a particular type of request. For example, you can implement the [IntentRequestHandler interface](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-core/src/com/amazon/ask/dispatcher/request/handler/impl/IntentRequestHandler.java) to handle one or more of your skill's intents. `instanceof` checks and casts are not necessary when using these type specific interfaces. We will continue to look at ways to improve access to nested request attributes, but I'm hopeful that this change greatly improves the intuitiveness of writing request handling logic.
