### ISSUE TITLE
access to locale moved down to specific request types

### ISSUE THREAD

**Issue by vgoldman** [amzn/alexa-skills-kit-java#150]
## I'm submitting a...

<pre><code>[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Before 2.6.0 locale could be retrieved from the Request level as
 String locale = input.getRequestEnvelope().getRequest().getLocale();
It is still documented here:
https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/docs/en/Managing-In-Skill-Purchases.rst

## Current Behavior

Since 2.6.0 locale was moved to specific request types which makes little sense, now we need to go through extra steps of checking request type and casting the request before locale can be accessed.
Locale should not even be a property of a request, it should be an attribute of the device level (since that's where it is currently set on user's side).

## Steps to Reproduce (for bugs)
```
Invoke 
String locale = input.getRequestEnvelope().getRequest().getLocale();
on 2.6.0 or later
```

## Possible Solution
```
Please consider moving locale to device level where it belongs.
```

## Your Environment

* ASK Java SDK version used: 2.6.0, 2.7.1
* Operating System and version: Lambda

## Java Info

* Java version used for development: 1.8

**Comment by nikhilym** [comment]
Hey @vgoldman , thanks for pointing out the documentation issue. We will be updating it accordingly. 

As for moving the locale to device level (per your possible solution), that is incorrect, since there are certain requests, like Skill event requests (eg: [SkillEnabledEvent Request](https://developer.amazon.com/docs/smapi/skill-events-in-alexa-skills.html#skill-enabled-event) etc.) that do not have locale information. This is the reason for moving locale to specific request types.

**Comment by vgoldman** [comment]
Hi Nikhil,
Why not move it to context and populate only when available?
Or even move it out completely to the Settings API?
https://developer.amazon.com/docs/smapi/alexa-settings-api-reference.html
This is after all one of the device settings, it's not like a user can modify locale within one session between requests. 
Having it anywhere on the request level does not make much sense, that I agree with.

**Comment by nikhilym** [comment]
The SDK models the request JSON in the format specified [here](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html). We cannot move that into a different location, which will lead to breaking changes. You can check the models in this [repo](https://github.com/alexa/alexa-apis-for-java)

**Comment by mauroarias** [comment]
Hi Nikhilym,

Could you please you give me an example (or point me to an one) of how to extract the language from the request. I'm checking your model but it is not obvious. I have the same problem to extract slots from the Request.

I'm trying to do:

```
public class LaunchRequestHandler implements RequestHandler {

    private final WelcomeService welcomeService;

    public LaunchRequestHandler(final WelcomeService welcomeService) {
        this.welcomeService = welcomeService;
    }

    @Override
    public boolean canHandle(HandlerInput input) {
        return input.matches(Predicates.requestType(LaunchRequest.class));
    }

    @Override
    public Optional<Response> handle(HandlerInput input) {
        
        final String locale = input.getRequest().getLocale(); //getLocale() is not there???
        
        String speechText = "Welcome to the Alexa Skills Kit, you can say hello";
        return input.getResponseBuilder()
                .withSpeech(speechText)
                .withSimpleCard("HelloWorld", speechText)
                .withReprompt(speechText)
                .build();
    }
}
```
Thanks a lot for helping me!!!

**Comment by mauroarias** [comment]
I think I understood... I need to cast my "HandlerInput" like this, please let me know if it's not the best practice:

```
public class LaunchRequestHandler implements RequestHandler {

    private final WelcomeService welcomeService;

    public LaunchRequestHandler(final WelcomeService welcomeService) {
        this.welcomeService = welcomeService;
    }

    @Override
    public boolean canHandle(HandlerInput input) {
        return input.matches(Predicates.requestType(LaunchRequest.class));
    }

    @Override
    public Optional<Response> handle(HandlerInput input) {
        
        final LaunchRequest launchRequest = (LaunchRequest) input.getRequest(); 

        final String locale = launchRequest.getLocale(); //getLocale() is finally there!!!

        String speechText = "Welcome to the Alexa Skills Kit, you can say hello";
        return input.getResponseBuilder()
                .withSpeech(speechText)
                .withSimpleCard("HelloWorld", speechText)
                .withReprompt(speechText)
                .build();
    }
}
```
Thx

**Comment by javier-ochoa** [comment]
@mauroarias You seem to have found the way to get the locale out of the Request.

I would recommend you to create an external component from the InputHandler to extract the locale from the request. 

```
public class LocaleResolver {

  public String resolve(Request request) {
    if (null == request) {
      return null;
    }

    if (request instanceof LaunchRequest) {
      return ((LaunchRequest) request).getLocale();
    }

    if (request instanceof SessionEndedRequest) {
      return ((SessionEndedRequest) request).getLocale();
    }

    if (request instanceof IntentRequest) {
      return ((IntentRequest) request).getLocale();
    }

    return null;
  }
}
```

Something along those lines. 

You can inject it into the InputHandler as you wish.

And you can return something else than null in case of locale not found, such an exception or some default locale you may want to have hardcoded, like english or spanish.

Hope this helps.

---

@nikhilym perhaps there could be a LocalizedRequest interface extending Request interface itself. This would help casting some classes such LaunchRequest, IntentRequest and others, which could simply extend that new interface and provide a getLocale method.

**Comment by breedloj** [comment]
Release 2.9.1 of the SDK restores the original behavior by exposing the locale property on the top level Request class.
