### ISSUE TITLE
Feature Request: Sample with APL

### ISSUE THREAD

**Issue by LorenzNickel** [amzn/alexa-skills-kit-java#154]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Since there's no complete APL-Sample provided here I'm requesting on for me and other developers to have a template wich we can play with.

## Current Behavior

At the moment there's no example with APL provided in this repository.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
Just a simple APL example, would be also possible to update the current helloworld example.

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by Chris-Liao** [comment]
@BlockLabTV we hear you and we have a team working on porting APL samples from NodeJS to Java. Please stay tuned.

**Comment by sungolivia** [comment]
Hey @BlockLabTV check out this sample [Pager Karaoke Device](https://github.com/alexa-labs/skill-sample-java-pager-karaoke) skill in Java!

**Comment by LorenzNickel** [comment]
Thanks, this helps me a lot <3 I think the issue is solved for me, but I still would like to leave it open until a sample ist provided in this repo (because this makes it a lot easier to find). Anyway, if you want you can close it of course, I do not know how you handle this.

**Comment by breedloj** [comment]
I've added a link to the new sample on this repo's README for reference. 😃
