### ISSUE TITLE
Session in Amazon Alexa using Java

### ISSUE THREAD

**Issue by akashjadhav511** [amzn/alexa-skills-kit-java#156]
Following is my conversasion:

I want to keep all answers given by user in session which I will be using at the end. But when I am trying to use session attribute it is just showing me last two answers and previous are getting erased.
 
User	Open welcome Insurance	   
Alexa	Hello, I am your conversational digital assistant from welcome Insurance.  
I can assist you to 
#) locate nearest agent of our Insurance 
#) provide insurance estimate	   
User	OK, give me the rough estimate of vehicle insurance?	   
Alexa	Please say vehicle type to provide specific details of your need.	   
User	Car	   
Alexa	Please say the year of manufacturing	   
User	2018	   
Alexa	Please say the type of insurance you have
#) Third party Insurance
#) Comprehensive/Regular Insurance	   
User	Third Party	   
Alexa	Mention the part having scratches or damages to the vehicle	   
User	Dented Bumper	   
Alexa	Ok. Mention the no of accidents or claims in current tenure?	   
User	4	   
Alexa 	Rough Estimate or amouunt required is 1500.	   
Alexa	I can assist you to 
#) locate nearest agent of our Inurance 
#) provide insurance estimate	   
User	Give me the details of nearest agent	   
Alexa	Your current location is identified as ‘<place name>’. 
If not, please say PIN code to provide specific details of your need.	   
User	PIN Code is 12121	   
Alexa	Play nearest agent details <play any one agent details>	   
		   
Alexa	I can assist you to 
#) locate nearest agent of our Inurance 
#) provide insurance estimate	   
User	Exit	   
Alexa	Thank you for your conversation with Welcome Insurance

**Comment by nikhilym** [comment]
Hey @akashjadhav511 , please update your issue with this [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/.github/ISSUE_TEMPLATE.md), so that we can investigate and help you better.

**Comment by Chris-Liao** [comment]
Hey @akashjadhav511 , would you create an issue so that we can help you better? Or you could paste some code snippet here. For session attribute value saving, make sure you assign different key to different value, otherwise it will be overridden.

**Comment by nikhilym** [comment]
Hey @akashjadhav511 , we are closing this issue since there was no update from you. Please create another one and follow the issue template, so that we can investigate the problem and help you in a better way.
