### ISSUE TITLE
samples Colorpicker Whats my Color intent

### ISSUE THREAD

**Issue by hupling** [amzn/alexa-skills-kit-java#157]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
![image](https://user-images.githubusercontent.com/11695964/48677507-47519f80-eb76-11e8-98d8-c9db876a537a.png)

[code](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/samples/colorpicker/src/com/amazon/ask/colorpicker/handlers/MyColorIsIntentHandler.java)
 
This line doesn't make anykind of sense. You can save for example "computer" as a color.
`if (favoriteColorSlot != null) {`
You should write.
`if(favoriteColorSlot.getResolutions().toString().contains("ER_SUCCESS_MATCH")) {`

**Comment by Chris-Liao** [comment]
Hey @hupling your suggestion makes sense, if user's answer will be limited in [LIST_OF_COLORS ](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/samples/colorpicker/models/en-US.json#L53-L83) defined in interaction model. Right now, it only pass in whatever value user provide and store as a session attribute.

I don't think `if (favoriteColorSlot != null)` is a bug, but using `Resolution` is definitely a improvement.

**Comment by Chris-Liao** [comment]
I'm closing this issue and will show usage of `Resolution` in another sample.
Feel free to reopen it if you have any questions.

**Comment by hupling** [comment]
This is dead code: [code](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/samples/colorpicker/src/com/amazon/ask/colorpicker/handlers/MyColorIsIntentHandler.java#L64-L71) It never gets executed even I say no color.

**Comment by Chris-Liao** [comment]
Double checking. You are right. Even though I pass in "My favorite color is", it never runs into else condition. I reopen it and will fix today. Thanks.

**Comment by Chris-Liao** [comment]
Hey @hupling , can you verify color picker sample is working correctly?

**Comment by hupling** [comment]
Probaly it will work, I didn't test it.
