### ISSUE TITLE
Read-the-docs build includes only single file

### ISSUE THREAD

**Issue by Bergmaier** [amzn/alexa-skills-kit-java#158]
Hi,
I've tried to download the documentation at https://readthedocs.org/projects/alexa-skills-kit-sdk-for-java/downloads/ and was hoping for it to contain the [Attributes documentation page](https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/Skill-Attributes.html) (and basically everything from the [`/docs/en` folder](https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/docs/en)), however the only resource (apart from the UI stuff in `/_static`) was an `index.html` containing the [start page](https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/).

**Comment by Chris-Liao** [comment]
Hey @Bergmaier , when you open the `index.html` in browser, you can find detail documentation by clicking the `+` button.

**Comment by Chris-Liao** [comment]
Hey @Bergmaier thanks for pointing that out, I'm fixing it.

**Comment by Chris-Liao** [comment]
Hi @Bergmaier, I just fixed it. Can you verify you can get these documents in your local? Thanks.

**Comment by Bergmaier** [comment]
Thanks for the quick response! Yes, the full documentation seems to be included in the download now. I had expected a multi-document webpage in the zip though, not everything inlined in the huge file. (It's your decision though). The only nuisance is that in the end of the document there are a few broken links to `.rst` files now (which in the online docs do link the respective subpages):

```html
<div class="section" id="guides">
<h1>Guides<a class="headerlink" href="#guides" title="Permalink to this headline">¶</a></h1>
<div class="section" id="setting-up-the-ask-sdk">
<h2><a class="reference external" href="Setting-Up-The-ASK-SDK.rst">Setting Up The ASK SDK</a><a class="headerlink" href="#setting-up-the-ask-sdk" title="Permalink to this headline">¶</a></h2>
<p>This guide will show you how to include the SDK as a dependency in your
Maven project.</p>
</div>
<div class="section" id="developing-your-first-skill">
<h2><a class="reference external" href="Developing-Your-First-Skill.rst">Developing Your First Skill</a><a class="headerlink" href="#developing-your-first-skill" title="Permalink to this headline">¶</a></h2>
<p>Walks you through step-by-step instructions for building the Hello World
sample.</p>
</div>
<div class="section" id="migrating-to-ask-sdk-v2-for-java">
<h2><a class="reference external" href="Migrating-To-ASK-SDK-v2-For-Java.rst">Migrating To ASK SDK v2 For Java</a><a class="headerlink" href="#migrating-to-ask-sdk-v2-for-java" title="Permalink to this headline">¶</a></h2>
<p>This guide will show you how to migrate an existing skill in v1 to v2 SDK.</p>
</div>
<div class="section" id="id1">
<h2><a class="reference external" href="SDK-Supported-Alexa-Capabilities.rst">SDK Supported Alexa Capabilities</a><a class="headerlink" href="#id1" title="Permalink to this headline">¶</a></h2>
<p>Provides a list of Alexa capabilities, that are supported in the ASK SDK.</p>
</div>
</div>
<div class="section" id="technical-documentation">
<h1>Technical Documentation<a class="headerlink" href="#technical-documentation" title="Permalink to this headline">¶</a></h1>
<div class="section" id="request-processing">
<h2><a class="reference external" href="Request-Processing.rst">Request Processing</a><a class="headerlink" href="#request-processing" title="Permalink to this headline">¶</a></h2>
<p>Covers how you can build request handlers to handle incoming requests,
exception handlers to handle errors in your skill, and use request and
response interceptors to perform tasks before or after handler
execution.</p>
</div>
<div class="section" id="skill-attributes">
<h2><a class="reference external" href="Skill-Attributes.rst">Skill Attributes</a><a class="headerlink" href="#skill-attributes" title="Permalink to this headline">¶</a></h2>
<p>Covers how skill attributes can be used on three different scopes
(request, session and persistent), to store and retrieve skill data.</p>
</div>
<div class="section" id="alexa-service-clients">
<h2><a class="reference external" href="Alexa-Service-Clients.rst">Alexa Service Clients</a><a class="headerlink" href="#alexa-service-clients" title="Permalink to this headline">¶</a></h2>
<p>Covers how service clients can be used by your skill to access Alexa
APIs.</p>
</div>
<div class="section" id="response-building">
<h2><a class="reference external" href="Response-Building.rst">Response Building</a><a class="headerlink" href="#response-building" title="Permalink to this headline">¶</a></h2>
<p>Covers how the Response Builder can be used to easily compose multiple
elements, like text, cards and audio, into a single response.</p>
</div>
<div class="section" id="skill-builders">
<h2><a class="reference external" href="Skill-Builders.rst">Skill Builders</a><a class="headerlink" href="#skill-builders" title="Permalink to this headline">¶</a></h2>
<p>Describes how to use Skill builders to easily create a configured
instance of the SDK.</p>
</div>
<div class="section" id="managing-in-skill-purchases">
<h2><a class="reference external" href="Managing-In-Skill-Purchases.rst">Managing In-Skill Purchases</a><a class="headerlink" href="#managing-in-skill-purchases" title="Permalink to this headline">¶</a></h2>
<p>Covers how you can manage in-skill products and the purchase experience
in your skills.</p>
</div>
<div class="section" id="javadoc-reference">
<h2><a class="reference external" href="http://ask-sdk-java-javadocs.s3-website-us-west-2.amazonaws.com">Javadoc Reference</a><a class="headerlink" href="#javadoc-reference" title="Permalink to this headline">¶</a></h2>
<p>Javadoc references from the latest version of the SDK.</p>
</div>
</div>
<div class="section" id="got-feedback">
<h1>Got Feedback?<a class="headerlink" href="#got-feedback" title="Permalink to this headline">¶</a></h1>
<p>Request and vote for Alexa features
<a class="reference external" href="https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote">here</a>!</p>
</div>
```

**Comment by nikhilym** [comment]
@Bergmaier , ReadTheDocs itself generates a full document when a user tries to download the HTML format of the docs. I do not think they provide us with an option to customize that. But that is a good point. We can look into that. However, if you are interested in generating the docs locally, you can download the `sphinx` python library and run the build on the `docs/en` directory by following [this](http://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build) doc.

With respect to the links being broken, since we currently add them as relative links to the index page, they will lead to broken links when downloaded locally. These can be changed to internal referenced doc links as mentioned [here](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-doc), so that they are adjusted even in local downloads and would fix this holistically.

**Comment by Chris-Liao** [comment]
Hey @Bergmaier , can you verify those broken links are working now?

**Comment by Bergmaier** [comment]
I'm afraid I cannot. They now have `….html` file extensions, but still point to files that don't exist in the zip. They would work if the zip contained multiple documents…

I understand that it might not be (easily) possible to avoid the full document generation, and I'm ok with that. I'm not interested in building the docs locally. If some links at the end of the document stay broken, so be it - the much more important issue of the missing content has been fixed (in some form or another), that's all what I was asking for. Feel free to close the issue, or leave it open if you want to further investigate in fixing the links.

**Comment by Chris-Liao** [comment]
@Bergmaier thanks for confirming you can download the full documentation. I suggest to clone the repository which contains all files you prefer in [en](https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/docs/en) folder.

Closing this issue, and will look for a way to improve ReadTheDocs reference links in the future.
