### ISSUE TITLE
Missing the new AudioPlayer directives.

### ISSUE THREAD

**Issue by jtgrassie** [amzn/alexa-skills-kit-java#16]
https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills

**Comment by jtgrassie** [comment]
I have added a pull request with the new functionality if anyone needs this now.

**Comment by bbatarelo** [comment]
Do we know when will this get merged/released?

**Comment by bclement-amazon** [comment]
I've added AudioPlayer directives to this branch with commit d52a5f418119d3a1b4320c93c1a60a5cc7e2c333
