### ISSUE TITLE
Can not disable signature check for local development 

### ISSUE THREAD

**Issue by ayoubabid** [amzn/alexa-skills-kit-java#161]
I try to test my app in localhost. I use a REST Client in Browser to send POST Request to my app.
In alexa code version 1 was there a "FLAG" in SpeechletServlet : "com.amazon.speech.speechlet.servlet.disableRequestSignatureCheck" when it true , then the signature check will be ignored. In the new version, this flag was deleted.
How can i disable this check ? or is there a signature/certificate already prepared for developer to test locally ?
Thanks !

**Comment by breedloj** [comment]
Hey, thanks for reaching out. We initially removed this feature for security concerns but I can definitely see cases where this functionality would be desired. We'll look into porting over the feature from the v1 SDK.

**Comment by Chris-Liao** [comment]
Hey @ayoubabid please stay tuned for next SDK release which includes this fix, or you can pull the latest source code.

**Comment by breedloj** [comment]
This feature is available in the 2.9.2 release of the SDK. Thanks again for the request!
