### ISSUE TITLE
after  adding ssl certificate in pom.xml helloworld getting error like java tag unrecognized 

### ISSUE THREAD

**Issue by shmayuri** [amzn/alexa-skills-kit-java#162]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

`
[pom.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-java/files/2618507/pom.txt)

`

**Comment by tianrenz** [comment]
Hi @shmayuri , 

could you provide more information on the issue? Preferably a copy of the pom.xl file you are using the and error message log?

Regards

**Comment by shmayuri** [comment]
Hi @tianrenz,
I attached pom file and error message log
<<<<<<<POM>>>>>
<?xml version="1.0"?>

-<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">

<modelVersion>4.0.0</modelVersion>

<groupId>alexa-skills-kit-samples</groupId>

<artifactId>helloworld</artifactId>

<packaging>jar</packaging>

<version>1.0</version>

<name>helloworld</name>

<url>http://developer.amazon.com/ask</url>


-<licenses>


-<license>

<name>The Apache License, Version 2.0</name>

<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>

</license>

</licenses>


-<developers>


-<developer>

<name>Alexa Skills Kit</name>

<email>ask-sdk-java@amazon.com</email>

<organization>Alexa</organization>

<organizationUrl>http://developer.amazon.com/ask</organizationUrl>

</developer>

</developers>


-<scm>

<connection>scm:git:https://github.com/amzn/alexa-skills-kit-java.git</connection>

<developerConnection>scm:git:https://github.com/amzn/alexa-skills-kit-java.git</developerConnection>

<url>https://github.com/amzn/alexa-skills-kit-java.git</url>

</scm>


-<dependencies>


-<dependency>

<groupId>com.amazon.alexa</groupId>

<artifactId>ask-sdk</artifactId>

<version>2.7.2</version>

</dependency>

</dependencies>


-<java fork="true" classpathref="java.sdk.classpath" classname="Launcher">

<sysproperty value="/home/aticara/ssl/java-keystore.jks" key="javax.net.ssl.keyStore"/>

<sysproperty value="test1234" key="javax.net.ssl.keyStorePassword"/>

</java>


-<build>

<sourceDirectory>src</sourceDirectory>


-<pluginManagement>


-<plugins>


-<plugin>

<groupId>org.apache.maven.plugins</groupId>

<artifactId>maven-compiler-plugin</artifactId>

<version>3.7.0</version>


-<configuration>

<source>1.8</source>

<target>1.8</target>

<forceJavacCompilerUse>true</forceJavacCompilerUse>

</configuration>

</plugin>

</plugins>

</pluginManagement>

</build>

</project>

<<<<<<<<<<<<<<<<<<<<<ERROR LOG>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

node14029:~/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld$ mvn assembly:assembly -DdescriptorId=jar-with-dependencies package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml: Unrecognised tag: 'java' (position: START_TAG seen ...me="Launcher"\n      classpathref="java.sdk.classpath" fork="true">... @38:53)  @ /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml, line 38, column 53
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project alexa-skills-kit-samples:helloworld:1.0 (/home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml) has 1 error
[ERROR]     Malformed POM /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml: Unrecognised tag: 'java' (position: START_TAG seen ...me="Launcher"\n      classpathref="java.sdk.classpath" fork="true">... @38:53)  @ /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml, line 38, column 53 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
[pom.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-java/files/2619049/pom.txt)

**Comment by breedloj** [comment]
From the Maven error it's clearly an issue with the way your pom.xml file is structured. I'm guessing the hyphens are not in the original file, but that was the first thing that jumped out at me. But the way you are passing system properties also appears to be invalid; refer to [this](https://stackoverflow.com/questions/3231797/specify-system-property-to-maven-project) post for some examples of how that can be accomplished.

**Comment by nikhilym** [comment]
Hey @shmayuri , did you try the approach mentioned by @breedloj ? Please update the issue if you are still facing problems

**Comment by shmayuri** [comment]
Hi @nikhilym ,i am facing same issue if syntax error when pen in internet explorer it will give error but i think problem is something else. And i already uploaded error log and pom file please check once. I am not able to upload pom.xml so i changed extension with pom.txt.

**Comment by nikhilym** [comment]
Hey @shmayuri , you can use the code blocks to add the pom file. Anyways, did you try changing the system properties tag to the one mentioned by @breedloj ? Please update the issue with your observations after the change and running mvn command

**Comment by shmayuri** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>alexa-skills-kit-samples</groupId>
  <artifactId>helloworld</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <name>helloworld</name>
  <url>http://developer.amazon.com/ask</url>
  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>Alexa Skills Kit</name>
      <email>ask-sdk-java@amazon.com</email>
      <organization>Alexa</organization>
      <organizationUrl>http://developer.amazon.com/ask</organizationUrl>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:https://github.com/amzn/alexa-skills-kit-java.git</connection>
    <developerConnection>scm:git:https://github.com/amzn/alexa-skills-kit-java.git</developerConnection>
    <url>https://github.com/amzn/alexa-skills-kit-java.git</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>com.amazon.alexa</groupId>
      <artifactId>ask-sdk</artifactId>
      <version>2.7.2</version>
    </dependency>
  </dependencies>
<java classname="Launcher"
      classpathref="java.sdk.classpath" fork="true">         
    <sysproperty key="javax.net.ssl.keyStore"
                 value="/home/aticara/ssl/java-keystore.jks" />
    <sysproperty key="javax.net.ssl.keyStorePassword"
                 value="test1234" />
</java>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
            <forceJavacCompilerUse>true</forceJavacCompilerUse>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  
</project>

Hi @nikhilym ,please check pom file and response after running mvn command.
a@node14029:~/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld$ mvn assembly:assembly -DdescriptorId=jar-with-dependencies package

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Malformed POM /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml: Unrecognised tag: 'java' (position: START_TAG seen ...ork="true" classpathref="java.sdk.classpath" classname="Launcher">... @79:74)  @ /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml, line 79, column 74
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project alexa-skills-kit-samples:helloworld:1.0 (/home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml) has 1 error
[ERROR]     Malformed POM /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml: Unrecognised tag: 'java' (position: START_TAG seen ...ork="true" classpathref="java.sdk.classpath" classname="Launcher">... @79:74)  @ /home/aticara/ssl/alexa-skills-kit-sdk-for-java-2.0.x/samples/helloworld/pom.xml, line 79, column 74 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by nikhilym** [comment]
Thanks for updating @shmayuri . Did you remove the hyphens (``-``) in the pom file as mentioned by @breedloj ? Also, does the mvn command works if you remove the ssl specific sys properties from the pom file? What is the full stack trace of errors when you run the mvn command with ``-e`` option?

**Comment by shmayuri** [comment]
Hi@nikhil, yes i removed

**Comment by breedloj** [comment]
@shmayuri can you clarify what you are trying to do here? Does the [original pom.xml](https://raw.githubusercontent.com/alexa/alexa-skills-kit-sdk-for-java/2.0.x/samples/helloworld/pom.xml) work for you? JVM arguments are typically passed when loading the JAR into the JVM, for example [this](https://stackoverflow.com/questions/5891123/specifying-jvm-arguments-when-calling-a-jar-file). Unless you are trying to set arguments for the Maven build environment or unit tests there is no way to embed them into the JAR itself.

**Comment by nikhilym** [comment]
Hey @shmayuri , can you please update the issue once you tried the approach mentioned by @breedloj ?

**Comment by shmayuri** [comment]
hi @nikhilym , I am referring this link " https://developer.amazon.com/docs/custom-skills/deploy-a-sample-skill-as-a-web-service.html" and if i am not doing changes in helloword pom.xml file it is building but when i add java tag with ssl certificate it is giving error like java tag unrecognized.

**Comment by shmayuri** [comment]
Hi @nikhilym ,Can i test alexa skill on local web server using python?if yes please share me link

**Comment by Chris-Liao** [comment]
Hi @shmayuri, you're referring to quite out of date documentation, which is not compatible with V2 SDK, sorry for that inaccurate information. I'll work on testing and updating the documentation. Please stay tuned. 
Unfortunately there's no local web server support in Python SDK at this moment, we're actively working on that as well, this [issue](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/53) may help you to host skill as web service.

**Comment by shmayuri** [comment]
Thank you @Chris-Liao

**Comment by Chris-Liao** [comment]
Hey @shmayuri , I want to check in with you and see if you are still having issues with this. Though we haven’t had a chance to update the documentation yet, I’ve communicated your feedback to the team to make sure the work is tracked

**Comment by pbheemag** [comment]
Closing issue due to issue-raiser inactivity. Can be re-opened if the issue still persists.
