### ISSUE TITLE
UnhandledSkillException

### ISSUE THREAD

**Issue by karlnicholas** [amzn/alexa-skills-kit-java#165]
Sorry, never mind.

**Comment by nikhilym** [comment]
Hey @karlnicholos, guess you figured out the problem. Can you please close the issue in case you are good with the SDK? Or update the issue with more information?

**Comment by karlnicholas** [comment]
Was a lucene bug.

**Comment by nikhilym** [comment]
Thanks @karlnicholas . New year wishes from SDK team!!
