### ISSUE TITLE
Can we save persistent attributes with SDK 2.11.0 using Java and without dynamo DB ?

### ISSUE THREAD

**Issue by gaurav229** [amzn/alexa-skills-kit-java#167]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by breedloj** [comment]
Hey there, if you can provide more details about what you're trying to do I can give you a more specific response, but generally speaking we only provide official support for using DynamoDB as your persistence layer. That said, the persistence layer is pluggable and you can create your own implementation of the [PersistenceAdapter](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk-core/src/com/amazon/ask/attributes/persistence/PersistenceAdapter.java) interface to call in to the persistence layer of your choice.

**Comment by Chris-Liao** [comment]
Hey @gaurav229, have you tried implementing PersistenceAdapter as suggested? Have you encountered any specific questions?

**Comment by Chris-Liao** [comment]
Close for inactivity. Please feel free to reopen for any problems.
