### ISSUE TITLE
Example for working Video APL directive

### ISSUE THREAD

**Issue by javier-ochoa** [amzn/alexa-skills-kit-java#168]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

I would like some sample code with a working video running on APL, since I have tried on my APL skills but no video runs, only black frame where the video player should be located.

In addition, the example could have information on what skilk configuration is needed, such as what intents are needed and other features that may be needed to be active for Video to work on APL.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by Chris-Liao** [comment]
Hey @javier-ochoa, can you provide more details in your APL skill so that we can better assist you. 
There is a sample skill demonstrating video usage in Node, [firetv-vlog sample](https://github.com/alexa-labs/skill-sample-nodejs-firetv-vlogs), and documentation for [APL video component ](https://developer.amazon.com/docs/alexa-presentation-language/apl-video.html). Hope this could help.

**Comment by javier-ochoa** [comment]
Hi there. Could you check the link for thw node project? 

I get redirected to the APL docs instead when clicking the link you posted.

Thanks.

**Comment by Chris-Liao** [comment]
Hey @javier-ochoa I just updated, can you check it now?

**Comment by Chris-Liao** [comment]
Hey @javier-ochoa, is Node sample helping you? Have you encountered any questions?

**Comment by javier-ochoa** [comment]
Yes, it is good. Thank you! @Chris-Liao

**Comment by Chris-Liao** [comment]
Hi @javier-ochoa, good to hear the sample helps you. Closing issue.
