### ISSUE TITLE
Stream Audio by AudioPlayerPlayDirective

### ISSUE THREAD

**Issue by navid1981** [amzn/alexa-skills-kit-java#172]
I'm trying to stream a mp3 file by alexa but getting error. When I change audio url to other mp3 or mp4 there is no error in Alexa developer console Test  but my Alexa doesn't play. The below is my code which I deployed in AWS lambda. I also tried commnted code but no success.

public Optional<Response> handle(HandlerInput handlerInput) {

        String token = handlerInput.getRequestEnvelope().getContext().getSystem().getApiAccessToken();
        if (token == null) token = "bbcpersian";
        String music="https://d1le29qyzha1u4.cloudfront.net/AWS_Podcast_Episode_228.mp3";

        return handlerInput.getResponseBuilder().
                addAudioPlayerPlayDirective(PlayBehavior.REPLACE_ALL,0L,"",token,music)
                .withShouldEndSession(true)
                .build();

//        Stream stream = Stream.builder()
//                .withUrl(music)
//                .withToken(token)
//                .withOffsetInMilliseconds(0L)
//                .build();
//
//        AudioItem audioItem = AudioItem.builder()
//                .withStream(stream)
//                .build();
//
//        PlayDirective playDirective = PlayDirective.builder()
//                .withPlayBehavior(PlayBehavior.REPLACE_ALL)
//                .withAudioItem(audioItem)
//                .build();
//
//        Response response = Response.builder()
//                .withDirectives(Collections.singletonList(playDirective))
//                .build();
//
//        Optional<Response> res=Optional.of(response);
//        return res;
    }

**This is my input:**
{
	"version": "1.0",
	"session": {
		"new": true,
		"sessionId": "amzn1.echo-api.session.2a0f1591-31c7-4260-b017-d118b9d9af57",
		"application": {
			"applicationId": "amzn1.ask.skill.3bcc7aeb-0b6c-4fba-9ee7-78427dc557a8"
		},
		"user": {
			"userId": "amzn1.ask.account.AG7HARD4X6VTXNYSAP6Y5C4EGHHYZA5OPKEEZSTK4WZLBYHN4Z2XIBFZVWBVFKWPSAMGN33NJNX756JGBD5LQJKJRSKLWKJXAUTZRRQDCBEVWQO567XZBOOV6U7OX3BKMNUFA6H3BJYTAITMA2J4DNECT4UIRUZKFASPOV4SFN5DPMSK4NRQUWBWV4DYXB3ZSEG3PVHBVDCV7YA"
		}
	},
	"context": {
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.3bcc7aeb-0b6c-4fba-9ee7-78427dc557a8"
			},
			"user": {
				"userId": "amzn1.ask.account.AG7HARD4X6VTXNYSAP6Y5C4EGHHYZA5OPKEEZSTK4WZLBYHN4Z2XIBFZVWBVFKWPSAMGN33NJNX756JGBD5LQJKJRSKLWKJXAUTZRRQDCBEVWQO567XZBOOV6U7OX3BKMNUFA6H3BJYTAITMA2J4DNECT4UIRUZKFASPOV4SFN5DPMSK4NRQUWBWV4DYXB3ZSEG3PVHBVDCV7YA"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AGUDJXB7HIAOQY6HZFIA3LR2UIHNZQA4WXHHDU77XYXIC4VYV5S3XU5SGBOYW2XE2DHU3N3HFFRA625TWPAIJK3AEL67WWU4CHQDMEKUZZOPXLLQXC6Q47PQP4XBWXN3TOG7GQUM7S2KFTBQLYJXYNKIZXHLGKVT4IAZHD2D2AFYAQENWCXH4",
				"supportedInterfaces": {
					"AudioPlayer": {}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjNiY2M3YWViLTBiNmMtNGZiYS05ZWU3LTc4NDI3ZGM1NTdhOCIsImV4cCI6MTU0ODMwNTAwNywiaWF0IjoxNTQ4MzA0NzA3LCJuYmYiOjE1NDgzMDQ3MDcsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUdVREpYQjdISUFPUVk2SFpGSUEzTFIyVUlITlpRQTRXWEhIRFU3N1hZWElDNFZZVjVTM1hVNVNHQk9ZVzJYRTJESFUzTjNIRkZSQTYyNVRXUEFJSkszQUVMNjdXV1U0Q0hRRE1FS1VaWk9QWExMUVhDNlE0N1BRUDRYQldYTjNUT0c3R1FVTTdTMktGVEJRTFlKWFlOS0laWEhMR0tWVDRJQVpIRDJEMkFGWUFRRU5XQ1hINCIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFHN0hBUkQ0WDZWVFhOWVNBUDZZNUM0RUdISFlaQTVPUEtFRVpTVEs0V1pMQllITjRaMlhJQkZaVldCVkZLV1BTQU1HTjMzTkpOWDc1NkpHQkQ1TFFKS0pSU0tMV0tKWEFVVFpSUlFEQ0JFVldRTzU2N1haQk9PVjZVN09YM0JLTU5VRkE2SDNCSllUQUlUTUEySjRETkVDVDRVSVJVWktGQVNQT1Y0U0ZONURQTVNLNE5SUVVXQldWNERZWEIzWlNFRzNQVkhCVkRDVjdZQSJ9fQ.kD86Rwnd_E9sHAmSbh5Ym25cZQy8YIq_GXOsM_sT3xsUq9CK1RtKH5nuVbNJ8EBvYAjkF4YX-9bWN_T3453U9MKbfJyaVcR_xcQcezn8ue3p9mCoUNFryKtRvC-3X6iyOeSX7Ar1CG57fta0r6SeGiuUSNGK86ucqO2xvVS9sjh49ZkarIJEAYd9j-81wjrKALWsWOEnV-tMiNZFAXJmbPkyNkZBeuiVI9nzFUfIejdEq8sTjOJ6vzBd6GqMkYtKsq-Kf3olYL4vCl1odYmYwKoEQJ3YiU01CefsAIIcD38DAiuxQBfSwgUE5GyzjCMHpOHQaXhs39JH02EgYq7p0Q"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			]
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.652340bf-8937-4acd-9129-25ac763150f8",
		"timestamp": "2019-01-24T04:38:27Z",
		"locale": "en-US",
		"intent": {
			"name": "PersianIntent",
			"confirmationStatus": "NONE"
		}
	}
}

**In Alexa developer console Test I got this pop up warning: Error Retrieving Device Rendering
with the below log:**
{
    "header": {
        "namespace": "System",
        "name": "Exception",
        "messageId": "d672d05b-79ce-45fb-aeb9-9e4f261bafd0"
    },
    "payload": {
        "code": "INTERNAL_SERVICE_EXCEPTION",
        "description": "Error reading entity from input stream."
    }
}

In AWS CloudWatch there is no error for my manual json input.

**Comment by Chris-Liao** [comment]
Hey @navid1981 , have you enable Audio Player Interface in developer console as [documented](https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#config) here?  Besides using Audio Player, you can also try [SSML audio tag](https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html#audio). Hope it helps.

For better understanding of your question, would be good if you follow [issue template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) to create issue.

**Comment by navid1981** [comment]
@Chris-Liao  thanks for responding. sorry that i didn't follow the template. I enabled Audio Player interface. By audio tag you mean in java code I add <audio>mp3url</audio> to my music String in my code?

I have two other questions:
1- I know that Alexa AudioPlayer is not supporting Youtube, but is there any way to stream from youtube video? like using youtube-dl (youtube-dl --get-url https://www.youtube.com/watch?v=XA6bS8TyN10) to get mp4 file
2-In case of live channel on youtube, since live channel use M3U8 File, is it possible alexa could stream from live channel or that file?
________________________________

**Comment by Chris-Liao** [comment]
Hey @navid1981 , for audio testing, you need to use Alexa mobile app or device, as [documented](https://developer.amazon.com/docs/devconsole/test-your-skill.html#alexa-simulator-limitations) here, developer console doesn't support audio player, but the Skill I/O section shows the AudioPlayer directives sent from your skill. 

Can you provide Cloudwatch log so that we can better assist.

For audio tag, I mean to include something like `<audio src="audio link" />` into Response using [`withSpeech()`](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/446cee0a0710b56ba76653667f415fb697041167/ask-sdk-core/src/com/amazon/ask/response/ResponseBuilder.java#L81). 

For video, have you tried [VideoApp interface](https://developer.amazon.com/docs/custom-skills/videoapp-interface-reference.html), which does support `m3u8`, or [APL video](https://developer.amazon.com/docs/alexa-presentation-language/apl-video.html).  Hope it helps.

**Comment by navid1981** [comment]
@Chris-Liao<mailto:notifications@github.com> I already set alexa mobile app and I have amazon echo. But I don't have echo show to active VideoApp interface. My questions: is it possible we stream audio from youtube video on amazon echo?
Is it possible to stream audio from youtube live on amazon echo?

I saw this https://github.com/ndg63276/alexa-youtube that works fine but not for live video. is there any way to implement that in JAVA using google API?
[https://avatars1.githubusercontent.com/u/24956497?s=400&v=4]<https://github.com/ndg63276/alexa-youtube>

GitHub - ndg63276/alexa-youtube: An Alexa skill to play the audio from YouTube videos<https://github.com/ndg63276/alexa-youtube>
An Alexa skill to play the audio from YouTube videos - ndg63276/alexa-youtube
github.com


________________________________

**Comment by nikhilym** [comment]
Hey @navid1981 , can you please update the issue with your observations? I guess since you closed the issue,  you could get the skill working. So please let the community know how you fixed it, so that any other developer who might have a similar issue in future can look into this. Thanks!!

**Comment by navid1981** [comment]
@nikhilym actually I couldn't fix the issue. Amazon support team are not helpful at all. Their answer are not related to my question. I have alexa app and amazon echo. Audio interface is supported m3u8 because I tested it, but sometimes give me error and you cannot find the reason of the error in alexa developer logs. because there is no information

**Comment by nikhilym** [comment]
I am reopening the issue @navid1981 . Let's try to get this work for you. To understand your issue in a better fashion, can you please update the issue or add an issue comment following this [issue template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/.github/ISSUE_TEMPLATE.md) ? This will help us get to know what did you try and on which version of the SDK you tried.

Also, I see your initial issue said you used an mp3 file `https://d1le29qyzha1u4.cloudfront.net/AWS_Podcast_Episode_228.mp3`, but later on you said an `m3u8` file. So can you let us know the exact input source you are trying with and the output experience?

**Comment by pbheemag** [comment]
Hi @navid1981 , we'd like to know if your issue has been resovled. If not, kindly provide an update regarding the issue so we could help you further.

**Comment by navid1981** [comment]
@pbheemag sorry for late reply. my issue was resolved.
Thanks

**Comment by ishataneja-18** [comment]
@navid1981 I am facing the same issue. 

Can you please help me how you fixed this?

**Comment by justme-justus** [comment]
https://xkcd.com/979/
