### ISSUE TITLE
Timestamp verifier tolerance milliseconds/seconds conversion issue

### ISSUE THREAD

**Issue by raseidl** [amzn/alexa-skills-kit-java#173]
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

According to [this guide](https://developer.amazon.com/de/docs/custom-skills/host-a-custom-skill-as-a-web-service.html) and the hello world example [here](https://github.com/alexa/skill-samples-java/blob/master/tidepooler/pom.xml), the com.amazon.speech.speechlet.servlet.timestampTolerance system property defines the tolerance, in seconds, and not in milliseconds, to allow when verifying the timestamp on a request. In the SDK V1 the system property was converted from seconds to milliseconds using TimeUnit.toMillis in the TimestampSpeechletRequestVerifier. In the new SDK V2 the system property is not converted to milliseconds. That causes the skill to fail during the startup with a SecurityException because milliseconds and seconds are mixed and compared.

## Expected Behavior
Like in the SDK V1 the SkillRequestTimestampVerifier constructor should get a TimeUnit as parameter for converting the com.amazon.speech.speechlet.servlet.timestampTolerance from seconds to milliseconds.

The old constructor with the TimeUnit parameter:

	public TimestampSpeechletRequestVerifier(long tolerance, TimeUnit unit)

Debug output from the SDK V1:

    2019-01-26 09:30:40.726 MEZ
	FdtTimestampSpeechletRequestVerifier verify: request timestamp: 1548491433000 (FdtTimestampSpeechletRequestVerifier.java:82)
	2019-01-26 09:30:40.727 MEZ
	FdtTimestampSpeechletRequestVerifier verify: tolerance: 100000 (FdtTimestampSpeechletRequestVerifier.java:83)
	2019-01-26 09:30:40.727 MEZ
	FdtTimestampSpeechletRequestVerifier verify: delta: 7726 (FdtTimestampSpeechletRequestVerifier.java:84)

As you can see the tolerance and the delta are held in milliseconds.

## Current Behavior

The new constructor without the TimeUnit parameter:

	public SkillRequestTimestampVerifier(long toleranceInMilliseconds)

Debug output from the SDK V2:

	2019-01-26 09:33:07.190 MEZ
	FdtSkillRequestTimestampVerifier verify: requestTimestamp: 1548491587000 (FdtSkillRequestTimestampVerifier.java:99)
	2019-01-26 09:33:07.190 MEZ
	FdtSkillRequestTimestampVerifier verify: toleranceInMilliseconds: 100 (FdtSkillRequestTimestampVerifier.java:101)
	2019-01-26 09:33:07.190 MEZ
	FdtSkillRequestTimestampVerifier verify: delta: 190 (FdtSkillRequestTimestampVerifier.java:100)

As you can see the toleranceInMilliseconds variable gets the system property in seconds assigned directly without any conversion to milliseconds.

## Steps to Reproduce (for bugs)
Upgrade from SDK V1 to V2 where the system property "com.amazon.speech.speechlet.servlet.timestampTolerance" is set in seconds and not in milliseconds.

## Possible Solution
Either correct the documentation everywhere to set the system property in milliseconds in V2 and not in seconds like in V1, or adjust the TimestampSpeechletRequestVerifier constructor to convert seconds to milliseconds again.

## Context
I tried to upgrade from SDK V1 to V2

## Your Environment

* ASK Java SDK version used: 2.11.2
* Operating System and version: Google App Engine (Debian GNU/Linux 9 (stretch))
* The skill is running as a servlet

## Java Info

* Java version used for development: 8

**Comment by pbheemag** [comment]
Hey, thanks for the feedback. PR #174 introduces a change to allow you to specify a TimeUnit on the verifier. It will be included in the next official release of the SDK.

**Comment by raseidl** [comment]
Thanks for the quick solution 👍
