### ISSUE TITLE
CommitMessages

### ISSUE THREAD

**Issue by LorenzNickel** [amzn/alexa-skills-kit-java#181]
The [PullRequestTemplate of the Node-SDK](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/PULL_REQUEST_TEMPLATE.md) says that their commits follow the [Conventional Commit Guideline](https://conventionalcommits.org/). Should commits in this repo also follow this and should this be added to the template of this repo?

**Comment by breedloj** [comment]
The process for releasing the SDK and related artifacts differs between the Node and Java SDKs, which was a contributing factor to the chosen commit message approach. We do not have any plans to change this for Java. Thanks for reaching out!
