### ISSUE TITLE
Intent Chaining with the Java SDK

### ISSUE THREAD

**Issue by ToddMason** [amzn/alexa-skills-kit-java#183]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Context
I'm trying to implement Intent Chaining and I'm not sure how to accomplish this with the Java SDK. Is the feature supported and if so are there any examples you could point me to? Thanks!
https://developer.amazon.com/blogs/alexa/post/9ffdbddb-948a-4eff-8408-7e210282ed38/intent-chaining-for-alexa-skill 
## Your Environment

* ASK Java SDK version used: 2.12.0
* Operating System and version:

## Java Info

* Java version used for development:

**Comment by ToddMason** [comment]
I solved my problem. I didn't understand how to create a new Intent. Intent.builder() was the key.
`			Intent i = Intent.builder().withName("PromptPin").build();
			return input.getResponseBuilder().addDelegateDirective(i).build();
`

**Comment by bgolson2309** [comment]
I had the same question...  thanks for the tip!
