### ISSUE TITLE
Is the code contains the ontology of AMRL and the model of it

### ISSUE THREAD

**Issue by lbda1** [amzn/alexa-skills-kit-java#185]
Is the code contains the ontology of AMRL and the model of it?

**Comment by lbda1** [comment]
Is the code contains the ontology of AMRL and the model of it?

**Comment by Chris-Liao** [comment]
Hey @lbda1 , would you please create an issue using this [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) to let us understand and assist you better?

**Comment by pbheemag** [comment]
Hi @lbda1 ,
Closing this issue due to reporter inactivity. Feel free to re-open this issue or post new queries using this [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new).
