### ISSUE TITLE
Documentation Request (Clarifying RequestHandlers)

### ISSUE THREAD

**Issue by allusai** [amzn/alexa-skills-kit-java#186]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am submitting a documentation request for the "Request Handlers" section on the "Request Processing" wiki page. I believe the wording of this section could be improved to make it clearer for first-time users what request handlers are and why they are important to Alexa skill development.

There are a few clarifications that I would make which I've included below.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:

## Java Info

* Java version used for development:

Current: “Request handlers are responsible for handling one or more types of incoming requests.”

New: *Request handlers* are perhaps the most important part of your Alexa skill. Whenever a user interacts with your Alexa skill, the message they send is handled by one or more of your request handlers. Each request handler is custom designed to handle a specific type of request made by the user.

Current: “You can create request handlers by implementing the RequestHandler interface, or a typed request handler interface, both of which consist of two methods.”

New: There are two ways to go about making a request handler. One is to implement the generic `RequestHandler` interface provided in the skills kit and another is to define a typed request handler interface. Both of these options will require us to define two methods.

*Note: The order given in the documentation snippet above is the `RequestHandler` interface first and then the typed request handler interface. But the sections come in the opposite order. That makes it more confusing to the reader, especially if this is their first time developing an Alexa Skill.

**Comment by allusai** [comment]
This is the link to the Wiki page, just for reference! 
https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/Request-Processing.html

**Comment by pbheemag** [comment]
Hi @allusai ,
Thank you for your feedback. Your feedback has been communicated to the team and I have a PR in review for few of your suggestions.

**Comment by allusai** [comment]
Hello Prashanth,

Thank you! I look forward to hearing back about the PR.

Best Wishes,
Sai Allu

**Comment by pbheemag** [comment]
The PR #187 has been merged. Closing this issue now.
