### ISSUE TITLE
Error while using DynamicEntitiesDirective and UserEvent

### ISSUE THREAD

**Issue by FelixT42** [amzn/alexa-skills-kit-java#192]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

First i implemented the ClickHandler for a List in APL. This is working without problems, till I added an DynamicEntitiesDirective. After that my ClickHandler ends in an INTERNAL_SERVICE_ERROR and no response is shown in the simulator, so debugging is difficult

## Expected Behavior

That the Handler who should Handle the Click and also the voice intent creates and response and shows this on Echo or Simulator

## Current Behavior

I could see that the ClickHandler genarates an valid response, but it is not show in the simulator. 
At the Moment i can only use one of both (ClickHandler oder Dynamic Entities)

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Context

I try to implement a quiz application where the use could select an answer with clicking on the right one or use the text to make an answer. 

## Your Environment

* ASK Java SDK version used: 2.15.0 and 2.16.0
* Operating System and version: Win 10 pro

## Java Info

* Java version used for development: 1.8

**Comment by nikhilym** [comment]
Hi @junk999 , Although this seems to be a service issue from the simulator side, just to be sure, can you please provide the handler class code-snippet that was leading to this error?

**Comment by FelixT42** [comment]
Hi thanks for the response.  I here is the code of my clickhandler 
`QuestionIntentHandler questionIntentHandler = new QuestionIntentHandler();
			return questionIntentHandler.handle(input);`

and the code snipet from my QuestionIntentHandler() that causes this error: 
`Optional<Response> resp = input.getResponseBuilder()`
`					.withSpeech(speechText)`	
`					.withReprompt(question)`
`					.addDirective(dynamicEntitiesDirective)`
`					.addDirective(documentDirective)`
`					.withShouldEndSession(false)`
`					.build();`

`			return resp;`

and this is an example how I created the DynamicEntities:
`		// Slot D`
`		synonyms = new ArrayList<String>();`
`		synonyms.add("d");`
`		synonyms.add("4");`
`		synonyms.add(answer4);`

`		entity = Entity.builder()`
`				.withName(EntityValueAndSynonyms.builder()`
`						.withValue("D")`
`						.withSynonyms(synonyms)`
`						.build())`
`				.build();`

`		entities.add(entity);`

`		//Create directive and return them`
`		DynamicEntitiesDirective replaceEntityDirective = DynamicEntitiesDirective`
`                .builder()`
 `               .addTypesItem(EntityListItem.builder()`
 `                               .withName("Antwort_Char")`
`                                .withValues(entities)`
`                                .build())`
`                .withUpdateBehavior(UpdateBehavior.REPLACE)`
`                .build();`
		

`		return replaceEntityDirective;`

I have also tested the skill on the "EchoShow", with the same behavior.

**Comment by breedloj** [comment]
Hey, sorry for the lack of response on this issue. We've reached out to our internal service teams to take a look at your issue as this does not appear to be related to the SDK itself. Can you confirm you are still seeing this behavior? Thanks!

**Comment by FelixT42** [comment]
Hey, yes I tested it again with the new ask-sdk version 2.17.2 and have the same behavior. 
Best regards

**Comment by breedloj** [comment]
Thanks for the update. I'll let the service team know and pass along any updates I get or if I need any additional details from your side. Thanks again for your patience.

**Comment by FelixT42** [comment]
I tested it again today and now it is working. 

Thanks for the Help!

**Comment by breedloj** [comment]
Awesome! Glad to hear you got it sorted. Feel free to open a new issue if you run into any other problems.
