### ISSUE TITLE
ExceptionHandlers response not catched by ResponseInterceptors

### ISSUE THREAD

**Issue by javier-ochoa** [amzn/alexa-skills-kit-java#197]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X] Other... Please describe:  A question about the SDK
</code></pre>

I am confused on why ExceptionHandlers are not catched by ResponseInterceptors.

## Expected Behavior
Any ExceptionHandler should produce a response, given to the user, and that should be catched by any ResponseInterceptor.

## Current Behavior
ExceptionHandler responses are not catched by ResponseInterceptors

## Steps to Reproduce (for bugs)
Create an ExceptionHandler, a ResponseInterceptor that logs the response and force the skill to trigger that exception on a RequestInterceptor.

## Context
I have a ResponseInterceptor that catches the response and logs its value to a file in S3 for logging purposes. I expected ExceptionHandlers to work similar so that i could log the response as well..., but they didnt :(

**Comment by breedloj** [comment]
This is an interesting suggestion. The intention has been for exception handlers to fire last since, depending on which exception was thrown and where, any logic contained in response interceptors may not be relevant or function as expected. If there was enough demand for this feature it would have to be opt-in since changing the existing behavior could cause undesired results for currently implemented skills. Are there other use cases outside of logging in which this would be useful for you? If I can get some definitive use cases to justify this it's something we can consider adding.

**Comment by javier-ochoa** [comment]
hi @breedloj .
Thanks for your quick answer. 

For now I only need to log out. To be more specific, my task in hand is to be able to log out both input and output json and dump those to S3, both with same id number, so that I am able to match the request and the response later on using other tools, such Athena.

I managed to work the problem around by not extending from SkillStreamHandler  and doing my own implementation of the StreamHandler myself. I got it working nicely.

However, I do believe the basic idea of the ExceptionHandlers clashes against Amazon best practices and guidelines to build an Alexa skill, IMHO.

Amazon guidelines tell that the skill must be resilient and prepare to assume errors from backend so that the response to the user is contained and the experience is not affected. 

I may want to add a ResponseInterceptor that may change ANY response in some form to keep consistent the skill, but the ExceptionHandler response will not be so, and it is then when the SDK is an impediment itself to achieve such consistency on the skill.

If the ExceptionHandlers do return a response for the user to be heard, that response should be treated as any other response. How to achieve that or what code to implement over the SDK, I wont say, but the purpose of it may be something to think about.

Regardless, thanks to you and the team for the awesome job of the SDK!!

And you can close this issue if you wish.

**Comment by breedloj** [comment]
Thanks for the additional context. I do agree this could be a useful feature. I don't think it's something we'd immediately implement but as we continue to make improvements to the SDKs, and specifically response interceptors, we'll keep this in mind. I'm glad that you were able to find a workaround in the meanwhile. Thanks again for the suggestion and for reaching out. Feel free to reopen if you run into any other cases where this would be helpful.
