### ISSUE TITLE
SpeechletRequestSignatureVerifier not using Signature.verify's output 

### ISSUE THREAD

**Issue by mehnaazm** [amzn/alexa-skills-kit-java#2]
URGENT.
SpeechletRequestSignatureVerifier this Class 
`signature.verify(Base64.decodeBase64(baseEncoded64Signature
					.getBytes(Sdk.CHARACTER_ENCODING)))`
 line 90 in code. returns true if valid and false if invalid. this is not being checked why?

**Comment by surajr-amzn** [comment]
We've applied a fix as part of commit [7411ac4246115f5d3db03d9477a6818ad57aa977](https://github.com/amzn/alexa-skills-kit-java/commit/7411ac4246115f5d3db03d9477a6818ad57aa977
) .

**Comment by lettierimarco** [comment]
Why signature.verify returns always false to me, even if tested from service simulator?
Any ideas?

On the Speechlet servlet we do this:

try {
	byte[] serializedSpeechletRequest = IOUtils.toByteArray(request.getInputStream());
	AmazonSignatureVerifier.checkRequestSignature(serializedSpeechletRequest,
		request.getHeader("Signature"),request.getHeader("SignatureCertChainUrl"));
} catch (Exception e1) {
	    e1.printStackTrace();
	    int statusCode = HttpServletResponse.SC_BAD_REQUEST;
            response.setStatus(statusCode);
            return "{\"error\":\""+e1.getMessage()+"\"}";
}

**Comment by chenglim** [comment]
I'm having the same issue, always returning FALSE.
