### ISSUE TITLE
Response interceptors should be able to make changes to a response

### ISSUE THREAD

**Issue by rayarub** [amzn/alexa-skills-kit-java#206]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Currently, the interface for `ResponseInterceptor` is `void process(HandlerInput input, Optional<Response> response)`. As `Response` is immutable and the method is `void`, it is not possible for the interceptor to make any changes to the Response. This makes it impossible to do things like sanitize or otherwise modify the response's SSML before it makes it to the client.

## Current Behavior

I suggest providing a way for a response interceptor to actually make changes to the response it receives.

## Steps to Reproduce (for bugs)
N/A (feature request)

## Possible Solution
I would suggest one of two approaches:
1. Change the `process` method on the `ResponseInterceptor`/`GenericResponseInterceptor` interfaces so it can return a response instead of `void`. The interceptor could then either return a new, modified `Response` if it wants to make changes, or `null`/the original response if it doesn't want to make any changes. 
2. Provide a new `MutatingResponseInterceptor` or equivalent that could be implemented that provides this functionality. This would be more complex but would preserve backwards compatibility for existing implementations.

## Context

I'm trying to do some SSML sanitization/cleanup after my skill code has finished its work. Without something like this, I'd need to introduce this cleanup code into every single request handler instead, which would be far less practical.

## Your Environment

* ASK Java SDK version used: 2.17.2
* Operating System and version: N/A

## Java Info

* Java version used for development: N/A

**Comment by breedloj** [comment]
Hey Chris, thanks for the request. I 100% agree with you on this -- this prevents response interceptors from being super useful. I have had this on my mind for some time and was planning to do something similar to your first option (though both have their merits). Once I have a bit of bandwidth I'll get you a solution for this.

**Comment by breedloj** [comment]
Hey @rayarub, was hoping you might get a chance to look at my PR and provide any feedback you might have.

**Comment by rayarub** [comment]
@breedloj That change seems perfect to me, thanks!

**Comment by breedloj** [comment]
Awesome! Thanks for the feedback.

**Comment by pbheemag** [comment]
Closing this issue since the PR has been merged.
