### ISSUE TITLE
Alexa Skill builder using https

### ISSUE THREAD

**Issue by dhavaleneha** [amzn/alexa-skills-kit-java#217]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Help to use alexa skill builder as a https request
</code></pre>

## Expected Behavior

I want to call a webservice/servlet of my web application (Java) on building my Alexa Custom Skill

## Current Behavior

My webservice/ servlet is not being called. 

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
@WebServlet(name = "AskAlexa", urlPatterns = {"/askAlexa"})
public class AskAlexa implements RequestHandler {
    
    private static final Logger logger =
            Logger.getLogger(AskAlexa.class);

    @Override
    public boolean canHandle(HandlerInput input) {
        return input.getRequestEnvelope().getRequest() instanceof SkillEnabledRequest
                || input.getRequestEnvelope().getRequest() instanceof SkillDisabledRequest;
    }

    @Override
    public Optional<Response> handle(HandlerInput input) {
        logger.info("A skill event was recieved");

        if (input.getRequestEnvelope().getRequest() instanceof SkillEnabledRequest) {
            SkillEnabledRequest request = (SkillEnabledRequest) input.getRequestEnvelope().getRequest();
            logger.info("User enabled the skill at {}" + request.getTimestamp());
        }

        if (input.getRequestEnvelope().getRequest() instanceof SkillDisabledRequest) {
            SkillDisabledRequest request = (SkillDisabledRequest) input.getRequestEnvelope().getRequest();
            logger.info("User disabled the skill at {}" + request.getTimestamp());
        }
        
        return input.getResponseBuilder().withSimpleCard("MyTasks", "Travel to Europe")
             .withSpeech("foo")
             .withReprompt("bar").build();
        
    }
 AND THIS I HAVE ADDED IN HTTPS Defautl region on alexa developer setup

**https://www.etechschoolonline.com/webresources/askAlexa**

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: x.x.x
* Operating System and version:
POM.xml has this included

<dependency>
           
            <groupId>com.amazon.alexa</groupId>
            <artifactId>alexa-skills-kit</artifactId>
            <version>1.8.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.amazon.alexa</groupId>
            <artifactId>ask-sdk</artifactId>
            <version>2.3.4</version>
        </dependency>
        
        <dependency>
            <groupId>com.amazon.alexa</groupId>
            <artifactId>ask-sdk-servlet-support</artifactId>
            <version>2.3.5</version>
        </dependency>

## Java Info

* Java version used for development:

**Comment by soulshifter** [comment]
I am also unable to figure out the steps to host as a web service. How to make an endpoint to the main class ? You can have a look at https://github.com/TheSilentHorizon/spring-boot-alexa
If it helps kindly revert back.

**Comment by dhavaleneha** [comment]
Thanks. Will check and revert.

**Comment by pbheemag** [comment]
Hi @soulshifter @dhavaleneha ,
We have updated the documentation to build and test a skill as a webservice locally, [here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/samples/helloworldservlet). Essentially, you should be extending `SkillServlet` (code snippet [here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/samples/helloworldservlet/src/main/java/com/amazon/ask/helloworldservlet/HelloWorldSkillServlet.java), which would serve as an entry point to your application) instead of implementing `RequestHandler` interface. Hope this helps.

**Comment by soulshifter** [comment]
Hi @pbheemag ,
I was able to test things locally using servlet-support but I want to host this as an HTTPS endpoint i.e. I want to make a RESTful API using Spring and the existing code in JAVA made with ASK-SDK (with minimal changes) and host it on a PaaS (Not Lambda) as an endpoint and finally Alexa can be able to call this endpoint.

**Comment by dhavaleneha** [comment]
Hi,

Thanks a ton. Will check and let you know.

Regards,
Neha

**Comment by pbheemag** [comment]
Hi @soulshifter,
This [link](https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html) has the information that you need to host your skill as a web service.

**Comment by pbheemag** [comment]
Closing this issue due to reporter inactivity. Feel free to re-open the ticket if the issue persists.

**Comment by dhavaleneha** [comment]
Hi, I was too caught up to give this a try. Will check and get back with results. Thanks.
