### ISSUE TITLE
German "Umlaute" ä/ü/ö getting formatted falsely

### ISSUE THREAD

**Issue by paulschuetz** [amzn/alexa-skills-kit-java#220]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Corretly send German Umlaute like that:
<speak>Sentence with an Umlaut: ü</speak>

## Current Behavior

The German "Umlaute" such as ä, ü, and ö are formatted falsely at some point, resulting in SSML like this:
<speak>Sentence with an Umlaut: Ã¼</speak>

**Comment by breedloj** [comment]
Hey Paul, thanks for reaching out. Can you give me some more details to help me repro this issue? Are you hosting your skill on AWS Lambda? From the point of view of the SDK, we don't do any sort of parsing that should strip out Unicode characters like this, so I'm trying to pinpoint if this is happening elsewhere in the response chain or possibly on the service side.

**Comment by paulschuetz** [comment]
Yes I am hosting the Java Skill in AWS Lambda. You could reproduce this issue if you return a response with an Umlaut, e.g. "This is an response with an Umlaut: Ä". If you include this text also in  a card you should see how it is displayed with bad formatting.

**Comment by breedloj** [comment]
Can you provide a code snippet showing how you're generating this response? I'm having trouble reproducing. What you can also try is manually invoking the Lambda function through the AWS Lambda console to verify the response coming out of the Lambda itself. This would help pinpoint whether it's an issue in the SDK and/or skill logic vs. a service side problem.

**Comment by paulschuetz** [comment]
`return handlerInput.getResponseBuilder().withSpeech("This sentence contains an Umlaut such as ä,ü, or ö.").withShouldEndSession(true).build();`

**Comment by LorenzNickel** [comment]
I think this is more likely an issue with your compiling process. I am working with this SDK and umlauts are working fine for me. Try to decompile your skill-jar with for example [jd-gui](https://github.com/java-decompiler/jd-gui/releases) and let us know if the umlauts are correctly encoded in your jar. I'm 97% percent sure that this is the source of your issue and that's not directly related to this sdk.

**Comment by paulschuetz** [comment]
Yes you as right!
Adding the following property to my pom.xml fixed the problem. Thanks for the hint.

```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
```
