### ISSUE TITLE
sonatype-2019-0371 vulnerability

### ISSUE THREAD

**Issue by idaho-guy** [amzn/alexa-skills-kit-java#226]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When I run a vulnerability test against my codebase, I don't want any critical vulnerabilities

## Current Behavior
We get a critical vulnerability with com.fasterxml.jackson.core:jackson-databind.

+--- com.amazon.alexa:ask-sdk:2.21.0
|    +--- com.amazon.alexa:ask-sdk-core:2.21.0
|    |    +--- com.amazon.alexa:ask-sdk-runtime:2.21.0
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.9
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.9.1 -> 2.9.9.2
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 -> 2.9.9
|    |    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.9
|    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.9
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 -> 2.9.9
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.9.9
|    |    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.9.9 

Found security vulnerability sonatype-2019-0371 with severity 8.5.

## Steps to Reproduce (for bugs)
```
Run tooling against codebase
```

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Context

 We need to remove vulnerabilities from apps we deploy to prod but this one a dependency of the ASK

## Your Environment

* ASK Java SDK version used: com.amazon.alexa:ask-sdk:2.21.0
* Operating System and version: MacOS Mojave 10.14.6 

## Java Info

* Java version used for development:  "1.8.0_221"

**Comment by breedloj** [comment]
Thanks for reaching out. Release 2.22.0 depends on Jackson 2.9.10 to address the security vulnerabilities.
