### ISSUE TITLE
Intent object is not part of Request class in sdk-core

### ISSUE THREAD

**Issue by painbank** [amzn/alexa-skills-kit-java#232]
## I'm submitting a Bug Report or Feature request.
Would like to access the slots in a received request from the HandlerInput class, however, Intent object is not part of the Request class.

## Expected Behavior
would expect the following function call to be available:

`Map<String, Slot> intentSlots = requestEnvelope.getRequest().getIntent().getSlots();`

## Current Behavior

The slots are not available to access ed from the request envelope.

## Possible Solution

Add the object to the ask-sdk-model Rquest class.

## Context
I am now writing JSON parsing code, which really should be done by the SDK.

v1.8 Java SDK.

**Comment by nikhilym** [comment]
Hi @painbank , thanks for raising the issue. I am a bit confused. `Intent` object is indeed a part of `IntentRequest` object, as can be seen [here](https://github.com/alexa/alexa-apis-for-java/blob/master/ask-sdk-model/src/com/amazon/ask/model/IntentRequest.java#L33). 

However, `Request` is a polymorphic type and is dynamically resolved to `LaunchRequest`/`IntentRequest`/`SessionEndedRequest` etc. depending on the request json that is passed to the skill. So, I think you need to type cast the `requestEnvelope.getRequest()` to `IntentRequest` before trying to access the slots. Or, if you are using the [Typed Intent Handlers](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-java/handle-requests.html#typed-request-handlers), the SDK automatically type casts the request. 

Please let us know if this helps or you are having some other issue.

**Comment by painbank** [comment]
yes that worked, thank you.  non issue and this can be closed.  I did a cast of the Request to IntentRequest.  Just wasn't intuitive is all.
