### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by kinisoftware** [amzn/alexa-skills-kit-java#237]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Hi guys!

A silly issue, I was just looking for a Changelog file or so. I am missing some way to know the new features, fixes and so on for each newly published version. Please, point me to the right resource if that already exists. People could follow/watch the file changes in order to be updated and that communication approach would be great for devs IMO.

Thanks in advance, you are doing an awesome job!
Happy New Year! :)

**Comment by pbheemag** [comment]
Hi @kinisoftware ,
Documentation pertaining to every release is posted [here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/releases). Let me know if this helps.

**Comment by kinisoftware** [comment]
Thank you very much @pbheemag! It totally helps! I've just subscribed to releases notifications. 

I'm closing the issue now :)
