### ISSUE TITLE
Not able to build the sample project - helloworld

### ISSUE THREAD

**Issue by ameyarvaidya** [amzn/alexa-skills-kit-java#253]
When I am trying to build the project hello world to create the jar file, I am getting below error -

[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.231 s
[INFO] Finished at: 2020-03-16T00:10:35-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project helloworld: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR] 

I tried couple of solutions mentioned in below thread but no luck -

https://stackoverflow.com/questions/29282515/maven-error-reading-assemblies-no-assembly-descriptors-found

Thanks in advance!

**Comment by Shreyas-vgr** [comment]
Hi @ameyarvaidya, thank you raising the issue, can you provide more information on steps to reproduce this issue if it still exists, we provide a [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) for issues to be raised.

**Comment by Rangan2** [comment]
I am facing the same issue.

**Comment by Shreyas-vgr** [comment]
Hi @Rangan2 , thank you raising the issue, can you provide more information on steps to reproduce this issue, we provide a [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) for issues to be raised.

**Comment by sattpat** [comment]
Closing the issue after 21 days of inactivity.
