### ISSUE TITLE
com.amazon.ask.exception.AskSdkException: Could not find a skill to handle the incoming request 	

### ISSUE THREAD

**Issue by chandramoulee18** [amzn/alexa-skills-kit-java#263]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Run with out any exception in AWS Lambda unit test case

## Current Behavior

Throwing Below error during AWS console Unit Testing- 
Could not find a skill to handle the incoming request: com.amazon.ask.exception.AskSdkException
com.amazon.ask.exception.AskSdkException: Could not find a skill to handle the incoming request
	at com.amazon.ask.SkillStreamHandler.handleRequest(SkillStreamHandler.java:92)

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
1. Download the sample Project from git hub - 
https://github.com/alexa/alexa-skills-kit-sdk-for-java/tree/2.0.x/samples/helloworld

2. Build the project successfully using Maven (in Eclipse IDE).
3. Uploaded as a *.jar file in AWS Skill console
4. Changed the Hander Name accordingly.
5. Unit tested in AWS console for the skill and view the lock in Cloud Watch.

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Your Environment

* ASK Java SDK version used: 2.30.1
* Operating System and version: Windows 10, Eclipse IDE

## Java Info

* Java version used for development: Java 8, Java 11

**Comment by Shreyas-vgr** [comment]
Hi @chandramoulee18, thanks for raising the issue, could you share the AWS console test event configuration and the error you receive on CloudWatch on running the sample hello world skill?

Here is the sample test configuration I used to test the skill on AWS lambda
```js
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.123456789012",
    "application": {
      "applicationId": "amzn1.ask.skill.987654321"
    },
    "user": {
      "userId": "amzn1.ask.account.testUser"
    },
    "attributes": {}
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.987654321"
      },
      "user": {
        "userId": "amzn1.ask.account.testUser"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      }
    }
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "amzn1.echo-api.request.1234",
    "timestamp": "2016-10-27T18:21:44Z",
    "locale": "en-US"
  }
}
```

**Comment by sattpat** [comment]
Closing issue after 28 days of inactivity. Please reopen if needed
