### ISSUE TITLE
ScoreKeeper DynamoDB Setup instructions have the wrong primary key type

### ISSUE THREAD

**Issue by rynfld** [amzn/alexa-skills-kit-java#27]
DynamoDB Setup instructions in the README for the ScoreKeeper sample say to use "Hash" as the primary key type when it should be "String".

**Comment by katariarahul** [comment]
Hi,
i am working on to setup scorekeeper for alexa from the link
https://github.com/amzn/alexa-skills-kit-java/blob/master/samples/src/main/java/scorekeeper/README.md.

I have setup everything as mentioned in the link but while doing testing from Service Simulator, i am getting following error in lambda (CloudWatch)

Class not found: scorekeeper.ScoreKeeperSpeechletRequestStreamHandler: class java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: scorekeeper.ScoreKeeperSpeechletRequestStreamHandler
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)

Can you please guide in getting this resolve. Thanks.
