### ISSUE TITLE
ServiceClientFactory in SMAPI SDK clashes with core one

### ISSUE THREAD

**Issue by morfeusys** [amzn/alexa-skills-kit-java#284]
## I'm submitting a bug report

Looks like `com.amazon.ask.model.services.ServiceClientFactory` hasn't any methods and clashes with the same class in the core sdk library. Thus there is impossible to use both in the single project.

**Comment by Shreyas-vgr** [comment]
Hi @morfeusys, Can you please update the issue based on the [template](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) provided? and also can you elaborate your issue?

**Comment by tkm22** [comment]
It is supposed to mean this class belong to both SMAPI and SDK model.https://github.com/alexa/alexa-apis-for-java/search?q=serviceClientFactory

**Comment by doiron** [comment]
closing, please feel free to re-open and explain the user scenario in which you need to include the SDK as well as the Model together.   thanks
