### ISSUE TITLE
mvn compile -- No sources to compile

### ISSUE THREAD

**Issue by k9keeper** [amzn/alexa-skills-kit-java#29]
I moved the code to .\src\main\java  and then it started to compile sources

**Comment by ZongwanAmz** [comment]
Added a <sourceDirectory> tag in pom. 
The current folder structure can be used with mvc compile now.

**Comment by RenatFaiz** [comment]
> sourceDirectory
Adding this tag resolve problem with "No source to compile".
Great thanks!
