### ISSUE TITLE
mvn:assembly

### ISSUE THREAD

**Issue by UltimateOgee** [amzn/alexa-skills-kit-java#3]
I am trying to complete step 6 with little luck. How exactly do I run mvn:assembly to create the file to upload to the lambda function?

Update:  build the pom.xml in netbeans after installing the maven plugin to netbeans, and this creates a folder containing 'alexa-skills-kit-1.0.java. Not sure if this helps but it is not a zip file, or have the same name as the one mentioned in step 6

I am using the netbeans IDE and so far I have created a new pom.xml file in my netbeans projects folder and built it.

Help appreciated

**Comment by pvasudev-amzn** [comment]
You can get more information from here:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/deploying-a-sample-skill-to-aws-lambda#Preparing a Java Sample to Deploy in Lambda

1. Download or clone the amzn/alexa-skills-kit-java GitHub repository.
2. Open a command line and navigate to the samples folder in the zip. This directory contains the pom.xml file.
3. Run the following command:

```    mvn assembly:assembly -DdescriptorId=jar-with-dependencies package```

This creates a .JAR file called alexa-skills-kit-samples-1.0-jar-with-dependencies.jar in the target directory.

If that doesn't work, can you please share the error message?

**Comment by UltimateOgee** [comment]
Thank you for the support. I got the skills up and running and am now able to experiment with skills in java.

**Comment by pvasudev-amzn** [comment]
Thanks for letting us know.

**Comment by The-crazy-one** [comment]
![capture](https://user-images.githubusercontent.com/34842779/37770142-671edc3c-2df9-11e8-8cda-7e3f43fbb7b9.JPG)
