### ISSUE TITLE
Issue while building maven project

### ISSUE THREAD

**Issue by naveen1988** [amzn/alexa-skills-kit-java#30]
I am new to maven, I gotta stuck while creating jar file. Please someone help me to resolve this issue.
Thanks in advance

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2017-01-27T11:41:31+05:30
[INFO] Final Memory: 5M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'assembly' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Naveen\.m2\repository), ibiblio.org (http://mirrors.ibiblio.org/pub/mirrors/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by patst** [comment]
Hey,
- Are you behind a firewall or using a proxy? That could cause the issue here. One way to specify proxy settings is the 'settings.xml' (usually in %USER_HOME%\.m2\setttings.xml) as described here: https://maven.apache.org/guides/mini/guide-proxies.html 
- which maven version are you using?

**Comment by bclement-amazon** [comment]
Hi naveen.
Thanks @patst for suggesting the firewall/proxy as this may be the issue.
I'm using Maven 3.3.9 and on a fresh clone and I wasn't able to repro this issue, so i'm closing this. Please re-open with more details if you are still unable to build.
