### ISSUE TITLE
Releases are outdated

### ISSUE THREAD

**Issue by wolkenschieber** [amzn/alexa-skills-kit-java#301]
The releases page for this repository lists version _2.38.1_ as most recent version. However maven ships version _2.42.0_. The pom file in the main branch `2.0.x` also has version _2.42.0_.

Wouldn't it make sense to
* add a release entry for _2.42.0_ 
* bump the version in the pom file

**Comment by doiron** [comment]
we just released 2.42.1 and created a release entry for it.  thanks

https://github.com/alexa/alexa-skills-kit-sdk-for-java/releases/tag/2.42.1
