### ISSUE TITLE
Missing CI on PRs

### ISSUE THREAD

**Issue by kkocel** [amzn/alexa-skills-kit-java#305]
Currently, there is no CI setup for this project. I would like to have it enabled to prevent merging code that does not compile.

I noticed that there is a travis file in the repo but it's not configured.

CC @doiron

**Comment by doiron** [comment]
yes thanks for creating this issue.  We just enabled the Branch protection yesterday and talked about adding checks shortly.  We can potentially this issue to track the changes.

**Comment by doiron** [comment]
added some CI safety check on PRs.
