### ISSUE TITLE
Provide clear steps

### ISSUE THREAD

**Issue by Jacksotnik** [amzn/alexa-skills-kit-java#34]
Hello. I wand to create new skill in Eclipse. But here i can only copy samples and test it. Can you please provide clear steps what i need do for to create lambda function for amazon skill from 0.

**Comment by sungolivia** [comment]
Hi were you able to figure this out? If not, [this](https://developer.amazon.com/alexa-skills-kit/alexa-skill-quick-start-tutorial) is short tutorial you might be looking for!
