### ISSUE TITLE
Lambda request Context is not preserved

### ISSUE THREAD

**Issue by eugene-mobile** [amzn/alexa-skills-kit-java#35]
`com.amazon.speech.speechlet.lambda.SpeechletRequestStreamHandler.handleRequest(InputStream, OutputStream, Context)` method receives Lambda Context as input, but the context is never passed to further processing. 
Would be nice to include it in SpeechletRequestEnvelope. 

Why it is so important? 
1. The context gives you access to remaining time for the lambda function. You can use the time to set timeouts for HTTP calls to your custom back-end. 
2. It gives you the AWS request ID that you can cross-reference with your CloudWatch logs.
3. It gives you access to Logger

**Comment by sungolivia** [comment]
Thanks for the feature request, we added this to our backlog.

**Comment by syedtalha** [comment]
Hi,

Just checking if there was any progress on this. 

We need this feature for the use case when we might need to differentiate between a prod aliased lambda function and it's dev version. 

Essentially, having access to the lambda functions ARN would enable us to tweak behaviours for dev and prod, within the same Lambda function, with different versions and aliases, without resorting to using environment variables.
