### ISSUE TITLE
Maven Central has alexa-skills-kit v1.3.0

### ISSUE THREAD

**Issue by baq** [amzn/alexa-skills-kit-java#46]
Hi,

I noticed that maven central has the latest ASK for Java at version 1.3.  However this github repo indicates via comments that it is at version 1.2.  I noticed that there are no other branches or tags, so it must be a copy of some Amazon internal repo.  When will this repo and its samples be upgraded to match your latest Maven release?

Thanks,
Baq

**Comment by mariokorte** [comment]
This repo is in sync with the current maven release of 1.3.1

**Comment by vg-appsdirect** [comment]
Seems like Amazon developers not using the Github release feature. All comments are about "Releasing 1.2", this location https://github.com/amzn/alexa-skills-kit-java/releases is empty. The Sdk.java source has this:
```
public final class Sdk {
    /**
     * The version number for this library.
     */
    public static final String VERSION = "1.0";
```
The Samples in pom.xml mention:
```
<dependency>
      <groupId>com.amazon.alexa</groupId>
      <artifactId>alexa-skills-kit</artifactId>
      <version>1.3.0</version>
      <scope>compile</scope>
    </dependency>
```
but in Gradle build.gradle you can see:
```
dependencies {
    compile 'com.amazon.alexa:alexa-skills-kit:1.1.2'
    compile 'com.amazonaws:aws-lambda-java-core:1.0.0'
    compile 'com.amazonaws:aws-java-sdk-dynamodb:1.9.40'
```

... and they already released verion 1.3.1 and uploaded it to https://jcenter.bintray.com/com/amazon/alexa/alexa-skills-kit/ ;)

So all seems like Java SDK is not a main priority and everyone focused on Node.js.

It would be helpful if some of the Amazon Alexa Skills Kit for Java would take some time and clean this Github repository or point us to some other place where they do active development so we can get updates and support.

**Comment by odintsovamz** [comment]
Thank you for pointing out these inconsistencies, we will clean them up with one of the upcoming releases.
I just want to point out that Sdk.VERSION is used in responseEnvelope.setVersion() call and actually refers to SPI version rather than SDK. So it's javadoc inaccuracy referring it to as "version number for this library". We'll try to reword it more appropriately in the future. Strategy for increasing version numbers for the SPI definitions is currently defined to keep it 1.0 unless breaking changes are introduced; and they haven't been introduced yet up to the latest released version.

**Comment by vg-appsdirect** [comment]
Would be also nice, if somebody would start looking at pull requests and open issues and respond to people. I've seen that some folks started cloning your repository just because they tired to wait for Amazon to respond to PR... Not good ;)

**Comment by odintsovamz** [comment]
vg-appsdirect, this is something we won't be able to incorporate with the next version, but I am planning to cover those in one of the subsequent releases, which I plan to have more often now. Feel free to reach out directly if needed.

**Comment by vgarmash** [comment]
@odintsovamz I think this ticket can be closed now.
