### ISSUE TITLE
Echo Show 1.4 release

### ISSUE THREAD

**Issue by WillCodeForEver** [amzn/alexa-skills-kit-java#48]
Hi, 
Do you know when the 1.4 code will be released in Maven Central and corresponding sample apps will be updated to show usage of new Template etc..?

We are starting to optimize our skill which is under development for regular Echo to support Echo show and waiting for these new features.

Thanks

**Comment by brendanclement** [comment]
1.4 Code is available on maven central - https://search.maven.org/#artifactdetails%7Ccom.amazon.alexa%7Calexa-skills-kit%7C1.4.0%7Cjar

We're working on updating the sample skills and should have some examples out shortly!

**Comment by WillCodeForEver** [comment]
thanks for the quick reply, looking forward to any kind of documentation describing these new features and how they can be used.  Meanwhile i've switched to the latest 1.4 and browsing the code for hints
