### ISSUE TITLE
Display.RenderTemplate and Other Directives in Response

### ISSUE THREAD

**Issue by sibbsnb** [amzn/alexa-skills-kit-java#49]
I don't see the Echo Show directives in the package com.amazon.speech.ui.

Documentation is wrong as well.

In documentation: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/display-interface-reference

`{
      "primaryText": {
        "textField": {
          "text": "See my favorite car",
          "type": "PlainText"
        }
      },
      "secondaryText": {
        "textField": {
          "text": "Custom-painted",
          "type": "PlainText"
        }
      },
      "tertiaryText": {
        "textField": {
          "text": "By me!",
          "type": "PlainText"
        }
      }
    }`

Correct which works on device:

`{
      "primaryText": {
          "text": "See my favorite car",
          "type": "PlainText"
      },
      "secondaryText": {
          "text": "Custom-painted",
          "type": "PlainText"
      },
      "tertiaryText": {
          "text": "By me!",
          "type": "PlainText"
      }
    }`

**Comment by brendanclement** [comment]
Hey @sibbsnb ,
The echo show directives are not in the com.amazon.speech.ui namespace

You can find them in com.amazon.speech.speechlet.interfaces.display. Here : https://github.com/amzn/alexa-skills-kit-java/tree/master/src/com/amazon/speech/speechlet/interfaces/display

You're right about the docs.

**Comment by sibbsnb** [comment]
Thanks, had made some changes within sdk, so kind of difficult to swap the sdk as is. Have to analyze the changes and incorporate the needed changes.

**Comment by bclement-amazon** [comment]
Docs got updated on Friday 6/30 - Good catch!

Closing as issues have been addressed
