### ISSUE TITLE
Dependency on com.amazonaws.services.lambda

### ISSUE THREAD

**Issue by Timmmm** [amzn/alexa-skills-kit-java#5]
If I download the source and add it to my (previously working with the Alexa Skills Kit 1.1 release) code, then I find that it depends on some Lambda classes. I'm not using Lambda and I can't see any documentation on how to get this code (maybe it is linked somewhere in your site but the location is really not obvious). E.g. in `SpeechletRequestStreamHandler`:

```
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;
```

**Comment by Timmmm** [comment]
And to answer my own question, you need the `aws-lambda-java-core` source from here:

https://github.com/aws/aws-lambda-java-libs

The docs should say this.

**Comment by bclement-amazon** [comment]
The dependencies of the Skills kit has now been included in the pom.xml file.
