### ISSUE TITLE
missing feature - selectable image for echo show

### ISSUE THREAD

**Issue by WillCodeForEver** [amzn/alexa-skills-kit-java#51]
Hi According to doc, List Images suppose to be selectable. 
I don't see this being implemented,

quote from doc:
```A list template displays a scrollable list of items, each with associated text and optional images. These images can be made selectable, as described in this reference.```

```com.amazon.speech.speechlet.interfaces.display.template.ListTemplate2.ListItem```  doesn't have "selectable" property or something similar....
I know that for "primaryText" I can set a RichText with action:

```
	TextContent tc = new TextContent();
	RichText text = new RichText();
	text.setText("<font size=\"1\"><action value='recipe_details'>" + name + "</action></font>");
        tc.setPrimaryText(text);
```

Will the above work? (Alexa Skill Simulator for Show doesn't make the item selectable with the above code).

Can you please clarify how to make the ListItem clickable/selectable??

thanks

**Comment by odintsovamz** [comment]
By "selectable" it here means they may be clicked on and ElementSelected event will fire (see https://github.com/amzn/alexa-skills-kit-java/blob/master/src/com/amazon/speech/speechlet/interfaces/display/request/ElementSelectedRequest.java ). There is no special property for this, they are "selectable" (aka clickable) by nature. To avoid confusion it's not images that are "selectable" but the whole "list items".

**Comment by WillCodeForEver** [comment]
Alexey,
Thank you for the reply. My initial thought was that it would be selectable but using the "Echo Show Simulator" under Alexa Skill Testing section didn't fire the "onElementSelected(..)" request.  

My Handler does implement the "Display" interface:
```public class MyFunctionHandler implements SpeechletV2, Display```

I am getting the actual Echo Show device tomorrow, so I'll give it a try from the actual device and see if it does fire the event.

Thanks again for the clarification!

**Comment by odintsovamz** [comment]
You are correct. Echo Show Simulator doesn't support it yet. It should work with the device.
