### ISSUE TITLE
Found lot of JavaProblems errors in download and import

### ISSUE THREAD

**Issue by gubs4u** [amzn/alexa-skills-kit-java#52]
Hi Amazon ASK Java Team,

Imported the code into eclipse and converted into maven projects and ran the maven install on the downloaded project. Found lot of java problems including library missing in many of the modules in scorekeeper, Tidepooler, httpcore modules missing and so on.

Thanks,
Gubendran

**Comment by odintsovamz** [comment]
Shoot me a direct email (found in profile) with steps you took and some screenshots to make it easier to follow through. Samples haven't been updated for some time now, we'll look into it.
