### ISSUE TITLE
Update samples pom file to alexa-skills-kit 1.4.0 

### ISSUE THREAD

**Issue by Sunny-Dee** [amzn/alexa-skills-kit-java#57]
The pom.xml file in the samples directory points to the alexa-skills-kit version 1.3.0, but we really need 1.4.0 for the new classes for the echo show. Can you update the pom file to avoid build errors?

**Comment by sungolivia** [comment]
At this point, samples directory pom.xml directs to alexa-skills-kit version 1.5.0 now.
Closing this issue
