### ISSUE TITLE
Synonyms support

### ISSUE THREAD

**Issue by codeamatic** [amzn/alexa-skills-kit-java#58]
Does the latest version of the java SDK support synonyms?

**Comment by sungolivia** [comment]
In Skill Builder Bet, they support synonyms.

**Comment by timguy** [comment]
Also on java side insight SDK they support synonyms. I used it.
I was also looking for an example. See documentation of the json and code like this:

```
		intent.getSlot("Bla").getResolutions().getResolutionAtIndex(0).getStatus()...
		intent.getSlot("Bla").getResolutions().getResolutionAtIndex(0).getValueWrapperAtIndex(0).getValue().getName()
```
