### ISSUE TITLE
Excluding shouldEndSession parameter from SpeechletResponse

### ISSUE THREAD

**Issue by omkar11** [amzn/alexa-skills-kit-java#63]
Hello,
I am working on 'Echo Show' skill using Java sdk. With '1.4.0' version, I was able to add 'Directives' to SpeechletResponse and most of the stuff is working fine.
But for video to work, the response **should not contain** 'shouldEndSession' parameter. As per link:
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/videoapp-interface-reference
It is mentioned as a note that: **"The shouldEndSession parameter must not be included in the response, even if the value is set to null."** 

My response object always contains 'shouldEndSession = false'. Is there any way not to include 'shouldEndSession' in the response using java sdk?

**Comment by meetsatheesh** [comment]
same issue. Does the SDK need to provide a response type other than speechletResponse ?

**Comment by odintsovamz** [comment]
Please upgrade to 1.4.1

in 1.4.1 response.setNullableShouldEndSession(null) will result in not generating shouldEndSession field

1.4.0 should not be used.
