### ISSUE TITLE
Getting Slot Type Value ID

### ISSUE THREAD

**Issue by MichZipp** [amzn/alexa-skills-kit-java#67]
Hello,

Currently, I wasn't able to find a way to get the slot type value Id.
This would be useful, to map a group of words (Synonyms) to one java object attribute.
Is there any plan to add this feature in the future?

Greetings,
Michael

**Comment by sebastiande** [comment]
If you mean the resolution of slots:

https://github.com/amzn/alexa-skills-kit-java/issues/59

**Comment by MichZipp** [comment]
Yeah, I think this is what i mean.
But which function do I have to call?

**Comment by sebastiande** [comment]
You don't have to call any functions ... My pull request is only doing the mapping of Amazon's JSON response to the Java object (only getting the slot from the intent to access the ResolutionsPerAuthority, which contains the status code and the values).

It's the newest version 1.5.0

**Comment by MichZipp** [comment]
I'm using the newest version 1.5.0 and I can't see your changes!

**Comment by sebastiande** [comment]
The pull request isn't merged yet. 
You have to use my fork of the SDK: https://github.com/sebastiande/alexa-skills-kit-java

Then u have the current Amazon SDK 1.5.0 with entitiy slot resoltion.

**Comment by MichZipp** [comment]
Thanks, got it!!
This is what I needed!
