### ISSUE TITLE
Is the Notification feature already included in the SDK?

### ISSUE THREAD

**Issue by MichZipp** [amzn/alexa-skills-kit-java#78]
Hello,

Since Alexa supports Notifications (https://www.amazon.com/gp/help/customer/display.html?nodeId=202165800), I was wondering if the functionality is already included in the SDK?
I wasn't able to find something so far.

If so, does anyone have an example of how to use it? 
If not, are there future plans to include this feature?

Greetings,
Michael

**Comment by sungolivia** [comment]
Hi Michael, unfortunately we do not support it at the moment.
