### ISSUE TITLE
Class not found error 

### ISSUE THREAD

**Issue by BalajiVenkatesan94** [amzn/alexa-skills-kit-java#8]
I created a simple Hello world Alexa Skill as an AWS Lambda using Java based onhttps://github.com/amzn/alexa-skills-kit-java/tree/master/samples/src/main/java/helloworld.

But when I tried to test my lambda function it returned the following error

{

"errorMessage": "Error loading class helloworld.HelloWorldSpeechletRequestStreamHandler: com/amazon/speech/speechlet/lambda/SpeechletRequestStreamHandler",

"errorType": "class java.lang.NoClassDefFoundError"

}

what needs to be done?

**Comment by vidhyarti** [comment]
What was the issue ? I am getting same error.

**Comment by BalajiVenkatesan94** [comment]
![capture](https://cloud.githubusercontent.com/assets/12086618/22073990/e1c0bb78-ddcc-11e6-8c36-92189cd293c6.PNG)

Make sure your folder structure is like above.
