### ISSUE TITLE
Images not showing up in cards

### ISSUE THREAD

**Issue by rajeshsubramanian** [amzn/alexa-skills-kit-java#9]
Images don't seem to be working for standard cards. I am assigning an image instance as below, but keep getting an 'No Image Found'  message on the card. The images in question are hosted on S3 and available publically.

```
Image image = new Image();
image.setSmallImageUrl("https://s3.amazonaws.com/rsubramanian-random/fireworks_small.png");
image.setLargeImageUrl("https://s3.amazonaws.com/rsubramanian-random/fireworks_large.png");
```

```
StandardCard card = new StandardCard();
card.setTitle("Title");
card.setText(cardText);
card.setImage(image);
```

**Comment by deegles** [comment]
Hi Rajesh,

I wasn't able to see the images you linked, did you enable [CORS](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) on the S3 bucket?

**Comment by rajeshsubramanian** [comment]
Ah ha...yes. That was the issue. Thank you and apologies - I have closed this issue.
