### ISSUE TITLE
SDK 2.0: Slot confirmation accepts "xyz" as Confirmed.

### ISSUE THREAD

**Issue by snh-png** [amzn/alexa-skills-kit-java#93]
## Expected Behavior

Slot confirmation should only accept the response "yes/yeah.." similar utterances as CONFIRMED. Likewise "no/nope.." as DENIED. For any other responses should be confirmed back again unless there's a yes/no response from user.

## Current Behavior

Right now, if the user is asked for a slot confirmation, and user responds back with some irrelevant phase, it accepts that as a CONFIRMATION.

## Your Environment

* ASK Java SDK version used: 2.0.0

**Comment by sungolivia** [comment]
Can you show the piece of code wherever you deal with slots?

**Comment by Snehasispanigrahi** [comment]
There's nothing do with my code here. I am using dialog delegate. The slot confirmation status value populates as CONFIRMED even if the user responded with "xyz". I was trying to elicit the same slot if the "confirmation status" returns DENIED. But it returns DENIED only if the user responded with "no".

`System.out.println("Slot confirmation status: "+someSlot.getConfirmationStatus());`

**Comment by memodoring** [comment]
Hi, can you please capture the details of the issue along with steps to reproduce it here: alexa.uservoice.com? It is not related to the SDK.
